## Determining the optimal number of hidden layers and neurons

Instead of Experimentation,we can follow the below methods:
<br>
1.Start Simple- start with smaller number and then increase the complexity
<br>
2.Grid Search/Random Search- to try different architectures
<br>
3.Cross-Validation- to evaluate the performance
<br>
4.Heuristic Rules-
<br>
no of neurons in hidden layer is between size of input layer and size of output layer
<br>
A common practice is to start with 1-2 hidden layers

In [1]:
#Modules required
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
#Preprocessing and scaler conversion
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
#gender Encode
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data[['Gender']])
data.head()
#geography encode
onehot_encoder_geo=OneHotEncoder()
onehot_encoder_geo_df=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(onehot_encoder_geo_df,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [4]:
onehot_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [ ]:
#create the train and test data and then scale them
X=data.drop('Exited',axis=1)
Y=data['Exited']
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=32)

scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)# we dont fit on the testing data

#no need to save the encoded and scaler files, aswe already did iter

In [31]:
#Function to try out different values for neurons and layers

def create_model(neurons=32,layers=1):
    model=Sequential()
    model.add(Dense(neurons,activation='relu',input_shape=(x_train.shape[1],)))
    for _ in range(layers-1):
        model.add(Dense(neurons,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return model

In [32]:
from scikeras.wrappers import KerasClassifier  #Keras Classifier helps to bridge the gap between keras modela nd sklearn ecosystem
#sklearn helps to do hyper tuning.
model=KerasClassifier(layers=1,neurons=32,build_fn=create_model,verbose=1)

In [33]:
#Grid Search parameters for hypertuning
param_grid={
    'neurons':[16,32,64,128],
    'layers':[1,2],
    'epochs':[50,100]
}

In [ ]:
#perform Grid Search CV
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=param_grid,n_jobs=1,cv=3,verbose=1,error_score='raise') 
#n_jobs- to tell number of cpus to use, cv= splitting data into no of sets and then start training
#fit the model
grid_result=grid.fit(x_train,y_train)

##Best parameters after fine tuning
print("Best :%f using %s" % ( grid_result.best_score_,grid_result.best_params_))

Fitting 3 folds for each of 16 candidates, totalling 48 fits
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5222 - accuracy: 0.7769
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4505 - accuracy: 0.7960
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.8048
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4170 - accuracy: 0.8146
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4092 - accuracy: 0.8247
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4027 - accuracy: 0.8305
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3962 - accuracy: 0.8371
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3898 - accuracy: 0.8412
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3828 - accuracy: 0.8451
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3763 - accuracy: 0.8491
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3701 - accuracy: 0.8534
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3643 - accuracy: 0.8532
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3600 - accuracy: 0.8554
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3561 - accuracy: 0.8564
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3526 - accuracy: 0.8582
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8584
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8609
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3455 - accuracy: 0.8616
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3437 - accuracy: 0.8618
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3421 - accuracy: 0.8629
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8648
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3398 - accuracy: 0.8626
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3385 - accuracy: 0.8614
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8624
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8620
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3361 - accuracy: 0.8644
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8633
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3351 - accuracy: 0.8626
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.8612
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8663
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8639
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8620
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8644
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8633
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8626
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8616
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8637
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8622
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8629
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8633
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8635
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8629
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8627
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8620
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8641
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8629
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8641
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8620
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8641
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8633
84/84 [==============================] - 0s 780us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7769
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4433 - accuracy: 0.8110
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4291 - accuracy: 0.8166
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8215
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4138 - accuracy: 0.8237
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4075 - accuracy: 0.8305
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4007 - accuracy: 0.8329
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3942 - accuracy: 0.8339
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3878 - accuracy: 0.8384
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3814 - accuracy: 0.8412
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3756 - accuracy: 0.8442
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3698 - accuracy: 0.8485
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3647 - accuracy: 0.8507
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3607 - accuracy: 0.8541
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3571 - accuracy: 0.8536
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3540 - accuracy: 0.8579
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3515 - accuracy: 0.8560
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8588
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3475 - accuracy: 0.8582
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.8596
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8605
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3428 - accuracy: 0.8618
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8618
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8616
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8614
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3392 - accuracy: 0.8607
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3381 - accuracy: 0.8627
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3374 - accuracy: 0.8624
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8631
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8624
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3360 - accuracy: 0.8641
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8654
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8644
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8654
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8642
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8644
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8639
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8656
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8663
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8654
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8656
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8644
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8663
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8665
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8663
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8650
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8667
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8672
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8650
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3306 - accuracy: 0.8671
84/84 [==============================] - 0s 868us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.7594 - accuracy: 0.5268
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.5069 - accuracy: 0.7823
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4538 - accuracy: 0.7981
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4323 - accuracy: 0.8056
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4189 - accuracy: 0.8159
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4073 - accuracy: 0.8255
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3967 - accuracy: 0.8318
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3865 - accuracy: 0.8388
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3770 - accuracy: 0.8457
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3683 - accuracy: 0.8521
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3610 - accuracy: 0.8556
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3550 - accuracy: 0.8588
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8596
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3466 - accuracy: 0.8607
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3434 - accuracy: 0.8620
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3408 - accuracy: 0.8633
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8641
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3365 - accuracy: 0.8645
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8650
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8660
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8654
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8663
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8675
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8682
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8678
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8671
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8684
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3277 - accuracy: 0.8688
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8684
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3267 - accuracy: 0.8688
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8680
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8697
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8676
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8673
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8663
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8673
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8688
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8682
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8686
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8690
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.8690
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8703
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8705
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8693
Epoch 45/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3232 - accuracy: 0.8697
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8708
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8703
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3227 - accuracy: 0.8693
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8690
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8708
84/84 [==============================] - 0s 909us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.7319
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4384 - accuracy: 0.8117
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4205 - accuracy: 0.8181
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4098 - accuracy: 0.8239
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4002 - accuracy: 0.8312
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3900 - accuracy: 0.8391
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3795 - accuracy: 0.8462
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8504
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3625 - accuracy: 0.8539
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3555 - accuracy: 0.8582
Epoch 11/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8609
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3470 - accuracy: 0.8612
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 0.8611
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8633
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3401 - accuracy: 0.8612
Epoch 16/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3386 - accuracy: 0.8618
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8624
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3354 - accuracy: 0.8635
Epoch 19/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8654
Epoch 20/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3338 - accuracy: 0.8635
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8644
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8633
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8635
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8656
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3302 - accuracy: 0.8657
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8644
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8648
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8620
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8635
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3279 - accuracy: 0.8642
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8657
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8642
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3263 - accuracy: 0.8684
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8650
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8661
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3258 - accuracy: 0.8663
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8678
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8676
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8687
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8687
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8693
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8684
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8652
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8697
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3227 - accuracy: 0.8695
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8674
Epoch 47/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.8674
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8697
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8672
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8672
84/84 [==============================] - 0s 929us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7560
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4391 - accuracy: 0.8057
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4172 - accuracy: 0.8179
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4031 - accuracy: 0.8245
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3908 - accuracy: 0.8361
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3792 - accuracy: 0.8399
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3697 - accuracy: 0.8468
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3620 - accuracy: 0.8504
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3565 - accuracy: 0.8524
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3523 - accuracy: 0.8552
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3487 - accuracy: 0.8566
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3463 - accuracy: 0.8575
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3441 - accuracy: 0.8567
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8586
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3407 - accuracy: 0.8616
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3390 - accuracy: 0.8614
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8611
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8616
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8618
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3359 - accuracy: 0.8612
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8620
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8633
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8635
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8637
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8639
Epoch 26/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8639
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8663
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8631
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3318 - accuracy: 0.8631
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8654
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8657
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8671
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8659
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8654
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8671
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8650
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8646
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8657
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8648
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8665
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8654
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8641
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8676
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3263 - accuracy: 0.8676
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8674
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8676
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8659
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8669
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8669
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8672
84/84 [==============================] - 0s 978us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5777 - accuracy: 0.7021
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4403 - accuracy: 0.8105
Epoch 3/50
167/167 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8223
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8307
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3980 - accuracy: 0.8313
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3885 - accuracy: 0.8376
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3794 - accuracy: 0.8431
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3704 - accuracy: 0.8508
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8523
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3550 - accuracy: 0.8564
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3498 - accuracy: 0.8594
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3453 - accuracy: 0.8626
Epoch 13/50
167/167 [==============================] - 0s 3ms/step - loss: 0.3416 - accuracy: 0.8639
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3388 - accuracy: 0.8646
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.8667
Epoch 16/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3347 - accuracy: 0.8667
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8665
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8673
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8648
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8658
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8658
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8669
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8665
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8682
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8675
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8665
Epoch 27/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3257 - accuracy: 0.8680
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8671
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8673
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8690
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8671
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8690
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8671
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8669
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8684
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8680
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8693
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8690
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3218 - accuracy: 0.8667
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3216 - accuracy: 0.8671
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3213 - accuracy: 0.8675
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3209 - accuracy: 0.8691
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3207 - accuracy: 0.8688
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3206 - accuracy: 0.8690
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8701
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3200 - accuracy: 0.8686
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3193 - accuracy: 0.8706
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3193 - accuracy: 0.8691
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3195 - accuracy: 0.8712
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8697
84/84 [==============================] - 0s 862us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4941 - accuracy: 0.7791
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4155 - accuracy: 0.8183
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3957 - accuracy: 0.8320
Epoch 4/50
167/167 [==============================] - 0s 3ms/step - loss: 0.3813 - accuracy: 0.8444
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3687 - accuracy: 0.8504
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3591 - accuracy: 0.8569
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3520 - accuracy: 0.8558
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3469 - accuracy: 0.8582
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8622
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3415 - accuracy: 0.8612
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8614
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8609
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8639
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8633
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8627
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8629
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8631
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8657
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8629
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3302 - accuracy: 0.8654
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8661
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8633
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8659
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8654
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8678
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3265 - accuracy: 0.8667
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8680
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3258 - accuracy: 0.8654
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8676
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8667
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8659
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3241 - accuracy: 0.8682
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.8691
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8682
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8704
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8693
Epoch 37/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3217 - accuracy: 0.8676
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8693
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8699
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8719
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8702
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3193 - accuracy: 0.8697
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3188 - accuracy: 0.8717
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8695
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8689
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8717
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8697
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8702
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8738
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8699
84/84 [==============================] - 0s 917us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5024 - accuracy: 0.7731
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8221
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3956 - accuracy: 0.8335
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3805 - accuracy: 0.8431
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3677 - accuracy: 0.8485
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3580 - accuracy: 0.8541
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3518 - accuracy: 0.8556
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3476 - accuracy: 0.8556
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3449 - accuracy: 0.8562
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3423 - accuracy: 0.8597
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3403 - accuracy: 0.8603
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8616
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8612
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8601
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3368 - accuracy: 0.8588
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8624
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8635
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8635
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8624
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8612
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8639
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8657
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8637
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8635
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8661
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8650
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8665
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8652
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8642
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8650
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3279 - accuracy: 0.8669
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8665
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8656
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8686
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3264 - accuracy: 0.8661
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8646
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8682
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3254 - accuracy: 0.8669
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8669
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8686
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8687
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8669
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8697
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8680
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8686
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8682
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8686
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8687
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3216 - accuracy: 0.8684
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8702
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4874 - accuracy: 0.7859
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8189
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4000 - accuracy: 0.8313
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3828 - accuracy: 0.8421
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3665 - accuracy: 0.8510
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3542 - accuracy: 0.8581
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3455 - accuracy: 0.8615
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8616
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 0.8658
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8667
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8673
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8648
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8680
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8673
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8675
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8693
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8688
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8690
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8682
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8718
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8716
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8688
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8693
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8695
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8720
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8695
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8690
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8691
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8691
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3189 - accuracy: 0.8712
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8718
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8706
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8699
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8686
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3169 - accuracy: 0.8697
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3169 - accuracy: 0.8708
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3161 - accuracy: 0.8716
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8691
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8705
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8729
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3153 - accuracy: 0.8721
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3148 - accuracy: 0.8720
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8723
Epoch 44/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3139 - accuracy: 0.8740
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3135 - accuracy: 0.8716
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8733
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8714
Epoch 48/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3127 - accuracy: 0.8723
Epoch 49/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3119 - accuracy: 0.8727
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8695
84/84 [==============================] - 0s 915us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4948 - accuracy: 0.7592
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4030 - accuracy: 0.8320
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3806 - accuracy: 0.8434
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3644 - accuracy: 0.8560
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3539 - accuracy: 0.8594
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8607
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3438 - accuracy: 0.8624
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3415 - accuracy: 0.8616
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8641
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3368 - accuracy: 0.8637
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8620
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8624
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8629
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8633
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8618
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8648
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8665
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3258 - accuracy: 0.8663
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8676
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8659
Epoch 21/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3225 - accuracy: 0.8676
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8669
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3213 - accuracy: 0.8680
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3207 - accuracy: 0.8669
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8695
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8687
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8695
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8697
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3151 - accuracy: 0.8716
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8714
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8701
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8691
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3119 - accuracy: 0.8695
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3103 - accuracy: 0.8706
Epoch 35/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3093 - accuracy: 0.8714
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3081 - accuracy: 0.8761
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8736
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3079 - accuracy: 0.8738
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8742
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8757
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3042 - accuracy: 0.8749
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8768
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8738
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8742
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8781
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.8766
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3003 - accuracy: 0.8755
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2994 - accuracy: 0.8753
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8761
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2975 - accuracy: 0.8759
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4740 - accuracy: 0.7887
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4062 - accuracy: 0.8256
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3847 - accuracy: 0.8414
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3664 - accuracy: 0.8494
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3550 - accuracy: 0.8566
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3477 - accuracy: 0.8567
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3448 - accuracy: 0.8571
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8599
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8620
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8624
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8627
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8641
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8631
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8648
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8654
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8644
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3287 - accuracy: 0.8684
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8691
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8689
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8663
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8686
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8657
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8706
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8712
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8676
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8721
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3211 - accuracy: 0.8701
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3210 - accuracy: 0.8714
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8684
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3190 - accuracy: 0.8717
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3184 - accuracy: 0.8723
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8742
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8731
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8736
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8706
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3156 - accuracy: 0.8740
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8721
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3144 - accuracy: 0.8747
Epoch 39/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3135 - accuracy: 0.8734
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3135 - accuracy: 0.8731
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8740
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3119 - accuracy: 0.8731
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8755
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8764
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8732
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3101 - accuracy: 0.8755
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8777
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3086 - accuracy: 0.8747
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8747
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8723
84/84 [==============================] - 0s 950us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4678 - accuracy: 0.7846
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3987 - accuracy: 0.8320
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3769 - accuracy: 0.8455
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3594 - accuracy: 0.8536
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3483 - accuracy: 0.8618
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3425 - accuracy: 0.8633
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8652
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8620
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8650
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8690
Epoch 11/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3283 - accuracy: 0.8658
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3259 - accuracy: 0.8705
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3255 - accuracy: 0.8673
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8706
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.8736
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8675
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8701
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8701
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8706
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8733
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8729
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8693
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8738
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3142 - accuracy: 0.8716
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3134 - accuracy: 0.8733
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3118 - accuracy: 0.8755
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3111 - accuracy: 0.8725
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3100 - accuracy: 0.8742
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3104 - accuracy: 0.8735
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3080 - accuracy: 0.8725
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8755
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8748
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3066 - accuracy: 0.8768
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8755
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8757
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3036 - accuracy: 0.8750
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8772
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8793
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8781
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3005 - accuracy: 0.8789
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8772
Epoch 42/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2996 - accuracy: 0.8795
Epoch 43/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2978 - accuracy: 0.8783
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2983 - accuracy: 0.8781
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2970 - accuracy: 0.8751
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8780
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2955 - accuracy: 0.8795
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2953 - accuracy: 0.8800
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2933 - accuracy: 0.8783
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2930 - accuracy: 0.8810
84/84 [==============================] - 0s 963us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7740
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 0.8061
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4184 - accuracy: 0.8254
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4012 - accuracy: 0.8380
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3879 - accuracy: 0.8432
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3746 - accuracy: 0.8476
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3639 - accuracy: 0.8511
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3549 - accuracy: 0.8562
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.8582
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3456 - accuracy: 0.8577
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3430 - accuracy: 0.8599
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3406 - accuracy: 0.8629
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8624
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8633
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3370 - accuracy: 0.8612
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8661
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8616
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8644
Epoch 19/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8635
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8656
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8639
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8654
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3287 - accuracy: 0.8676
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3283 - accuracy: 0.8665
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8650
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8665
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8671
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8680
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8682
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8708
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8671
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8671
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8697
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8684
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8689
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8687
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8682
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3207 - accuracy: 0.8686
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8676
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8674
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8691
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3193 - accuracy: 0.8701
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8699
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8689
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8712
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8678
Epoch 47/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3165 - accuracy: 0.8693
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8697
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8704
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3161 - accuracy: 0.8689
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7562
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4467 - accuracy: 0.8003
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4227 - accuracy: 0.8140
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4087 - accuracy: 0.8237
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3958 - accuracy: 0.8314
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3825 - accuracy: 0.8380
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3688 - accuracy: 0.8470
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3579 - accuracy: 0.8522
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3494 - accuracy: 0.8552
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3434 - accuracy: 0.8579
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8607
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8624
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8597
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8641
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8629
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8652
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8654
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8674
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8631
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3254 - accuracy: 0.8657
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3251 - accuracy: 0.8661
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8687
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8671
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.8680
Epoch 25/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3223 - accuracy: 0.8669
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8669
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8693
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8687
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8702
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8687
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8704
Epoch 32/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3166 - accuracy: 0.8697
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8699
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3147 - accuracy: 0.8731
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3143 - accuracy: 0.8725
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8719
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3140 - accuracy: 0.8717
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8706
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3128 - accuracy: 0.8684
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3120 - accuracy: 0.8712
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3116 - accuracy: 0.8716
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3112 - accuracy: 0.8725
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3105 - accuracy: 0.8719
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8714
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8725
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8734
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3080 - accuracy: 0.8746
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3080 - accuracy: 0.8725
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8753
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3079 - accuracy: 0.8719
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7795
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4588 - accuracy: 0.7979
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4327 - accuracy: 0.8060
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4206 - accuracy: 0.8148
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4129 - accuracy: 0.8217
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4070 - accuracy: 0.8300
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4016 - accuracy: 0.8335
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3953 - accuracy: 0.8384
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3890 - accuracy: 0.8435
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3801 - accuracy: 0.8444
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3700 - accuracy: 0.8495
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3604 - accuracy: 0.8558
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3509 - accuracy: 0.8568
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8607
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8609
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.8639
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8635
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8648
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8663
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8675
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8675
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8678
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8691
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8701
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3200 - accuracy: 0.8697
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8669
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3184 - accuracy: 0.8733
Epoch 28/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8727
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8710
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8731
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3156 - accuracy: 0.8731
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3150 - accuracy: 0.8714
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8729
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8736
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3125 - accuracy: 0.8736
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3123 - accuracy: 0.8727
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8716
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.8723
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3101 - accuracy: 0.8720
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3097 - accuracy: 0.8744
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8725
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3086 - accuracy: 0.8736
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8746
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8751
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.8751
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8740
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3066 - accuracy: 0.8755
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8755
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8765
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8761
84/84 [==============================] - 0s 933us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7500
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4132 - accuracy: 0.8311
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3859 - accuracy: 0.8447
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3648 - accuracy: 0.8530
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8590
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3433 - accuracy: 0.8601
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8635
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8659
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8635
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8665
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3263 - accuracy: 0.8646
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8672
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8654
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8691
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8680
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8704
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3143 - accuracy: 0.8704
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3131 - accuracy: 0.8719
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8732
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3097 - accuracy: 0.8712
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3077 - accuracy: 0.8725
Epoch 22/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3063 - accuracy: 0.8753
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3062 - accuracy: 0.8766
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8747
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8731
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3015 - accuracy: 0.8761
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8779
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8757
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8789
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8772
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2940 - accuracy: 0.8809
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8776
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2923 - accuracy: 0.8772
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2927 - accuracy: 0.8839
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2917 - accuracy: 0.8804
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2906 - accuracy: 0.8800
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2879 - accuracy: 0.8804
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2883 - accuracy: 0.8809
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2873 - accuracy: 0.8806
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2854 - accuracy: 0.8828
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2851 - accuracy: 0.8836
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2841 - accuracy: 0.8828
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8822
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2818 - accuracy: 0.8826
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2808 - accuracy: 0.8847
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2814 - accuracy: 0.8866
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2797 - accuracy: 0.8867
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2784 - accuracy: 0.8852
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2783 - accuracy: 0.8837
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2776 - accuracy: 0.8867
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4898 - accuracy: 0.7806
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4250 - accuracy: 0.8129
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4067 - accuracy: 0.8252
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3872 - accuracy: 0.8416
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3687 - accuracy: 0.8470
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3553 - accuracy: 0.8558
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3476 - accuracy: 0.8579
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3428 - accuracy: 0.8594
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8597
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.8607
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8624
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8637
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8624
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8659
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3258 - accuracy: 0.8661
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8648
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8667
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8684
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8671
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8663
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8682
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8676
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3130 - accuracy: 0.8701
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8686
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8706
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3081 - accuracy: 0.8706
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3066 - accuracy: 0.8729
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3050 - accuracy: 0.8736
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3045 - accuracy: 0.8714
Epoch 30/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3034 - accuracy: 0.8727
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3018 - accuracy: 0.8714
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3003 - accuracy: 0.8740
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3000 - accuracy: 0.8701
Epoch 34/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2985 - accuracy: 0.8770
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2965 - accuracy: 0.8732
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2963 - accuracy: 0.8755
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 0.8755
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2948 - accuracy: 0.8764
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8772
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2931 - accuracy: 0.8764
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2909 - accuracy: 0.8772
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2896 - accuracy: 0.8779
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2892 - accuracy: 0.8785
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2889 - accuracy: 0.8800
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2863 - accuracy: 0.8807
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2872 - accuracy: 0.8794
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2856 - accuracy: 0.8802
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2845 - accuracy: 0.8822
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2853 - accuracy: 0.8811
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2835 - accuracy: 0.8834
84/84 [==============================] - 0s 986us/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4751 - accuracy: 0.7979
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.4187 - accuracy: 0.8187
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3995 - accuracy: 0.8283
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3782 - accuracy: 0.8401
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3573 - accuracy: 0.8555
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8622
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8658
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3332 - accuracy: 0.8646
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8660
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8688
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8680
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8688
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3219 - accuracy: 0.8686
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8705
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8733
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8714
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8710
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3140 - accuracy: 0.8718
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8750
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3103 - accuracy: 0.8740
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8731
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8751
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8755
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3062 - accuracy: 0.8729
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8795
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8776
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3020 - accuracy: 0.8763
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3003 - accuracy: 0.8770
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.8785
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3000 - accuracy: 0.8795
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2982 - accuracy: 0.8776
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2977 - accuracy: 0.8778
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2965 - accuracy: 0.8768
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2953 - accuracy: 0.8802
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2939 - accuracy: 0.8823
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2950 - accuracy: 0.8802
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2937 - accuracy: 0.8813
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2923 - accuracy: 0.8800
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2920 - accuracy: 0.8834
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2905 - accuracy: 0.8811
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2899 - accuracy: 0.8800
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2875 - accuracy: 0.8849
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2877 - accuracy: 0.8830
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2886 - accuracy: 0.8823
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2860 - accuracy: 0.8821
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2871 - accuracy: 0.8836
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2866 - accuracy: 0.8832
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2852 - accuracy: 0.8860
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2824 - accuracy: 0.8851
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2841 - accuracy: 0.8841
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4597 - accuracy: 0.7992
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3912 - accuracy: 0.8436
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3616 - accuracy: 0.8549
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3431 - accuracy: 0.8607
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8652
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8648
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3261 - accuracy: 0.8674
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3213 - accuracy: 0.8693
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8706
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8695
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3123 - accuracy: 0.8721
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8742
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3050 - accuracy: 0.8753
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8764
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3012 - accuracy: 0.8761
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2986 - accuracy: 0.8759
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2976 - accuracy: 0.8776
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8772
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2925 - accuracy: 0.8798
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2903 - accuracy: 0.8811
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2876 - accuracy: 0.8817
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2863 - accuracy: 0.8804
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2860 - accuracy: 0.8821
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2825 - accuracy: 0.8822
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2809 - accuracy: 0.8824
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2791 - accuracy: 0.8817
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2773 - accuracy: 0.8832
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2751 - accuracy: 0.8851
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2746 - accuracy: 0.8869
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2719 - accuracy: 0.8867
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2697 - accuracy: 0.8851
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2680 - accuracy: 0.8858
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2658 - accuracy: 0.8882
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2668 - accuracy: 0.8912
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2633 - accuracy: 0.8886
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2621 - accuracy: 0.8899
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2597 - accuracy: 0.8903
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2591 - accuracy: 0.8909
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2567 - accuracy: 0.8907
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2563 - accuracy: 0.8926
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2546 - accuracy: 0.8914
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2513 - accuracy: 0.8941
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2503 - accuracy: 0.8952
Epoch 44/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2485 - accuracy: 0.8965
Epoch 45/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2468 - accuracy: 0.8939
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2467 - accuracy: 0.8972
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2428 - accuracy: 0.8957
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2429 - accuracy: 0.8986
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2435 - accuracy: 0.8978
Epoch 50/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2394 - accuracy: 0.8978
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4702 - accuracy: 0.7920
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3919 - accuracy: 0.8335
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3614 - accuracy: 0.8541
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3451 - accuracy: 0.8579
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3396 - accuracy: 0.8597
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8614
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8633
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8669
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8646
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3209 - accuracy: 0.8661
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8702
Epoch 12/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8706
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3147 - accuracy: 0.8678
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3110 - accuracy: 0.8716
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8723
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3070 - accuracy: 0.8736
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3046 - accuracy: 0.8759
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8744
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3003 - accuracy: 0.8742
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3005 - accuracy: 0.8736
Epoch 21/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2990 - accuracy: 0.8787
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8759
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2964 - accuracy: 0.8768
Epoch 24/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2949 - accuracy: 0.8759
Epoch 25/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2927 - accuracy: 0.8783
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2897 - accuracy: 0.8815
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2885 - accuracy: 0.8849
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2871 - accuracy: 0.8822
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2865 - accuracy: 0.8807
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2834 - accuracy: 0.8807
Epoch 31/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2816 - accuracy: 0.8807
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2819 - accuracy: 0.8828
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2792 - accuracy: 0.8875
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2759 - accuracy: 0.8864
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2782 - accuracy: 0.8875
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.8849
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2742 - accuracy: 0.8858
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2726 - accuracy: 0.8860
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2703 - accuracy: 0.8875
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2700 - accuracy: 0.8877
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2689 - accuracy: 0.8881
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2649 - accuracy: 0.8888
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2661 - accuracy: 0.8894
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2641 - accuracy: 0.8903
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2619 - accuracy: 0.8899
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2625 - accuracy: 0.8896
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2593 - accuracy: 0.8890
Epoch 48/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2600 - accuracy: 0.8907
Epoch 49/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2564 - accuracy: 0.8933
Epoch 50/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2572 - accuracy: 0.8901
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4529 - accuracy: 0.8060
Epoch 2/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3874 - accuracy: 0.8360
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3541 - accuracy: 0.8571
Epoch 4/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3379 - accuracy: 0.8630
Epoch 5/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8663
Epoch 6/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8663
Epoch 7/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8703
Epoch 8/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8695
Epoch 9/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8740
Epoch 10/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3132 - accuracy: 0.8733
Epoch 11/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.8735
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3098 - accuracy: 0.8772
Epoch 13/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3037 - accuracy: 0.8757
Epoch 14/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8772
Epoch 15/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2988 - accuracy: 0.8787
Epoch 16/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.8795
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2955 - accuracy: 0.8795
Epoch 18/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2938 - accuracy: 0.8802
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2891 - accuracy: 0.8819
Epoch 20/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2901 - accuracy: 0.8785
Epoch 21/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2873 - accuracy: 0.8841
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2845 - accuracy: 0.8849
Epoch 23/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2827 - accuracy: 0.8888
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2815 - accuracy: 0.8847
Epoch 25/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2795 - accuracy: 0.8900
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2783 - accuracy: 0.8853
Epoch 27/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2751 - accuracy: 0.8883
Epoch 28/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2741 - accuracy: 0.8890
Epoch 29/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2706 - accuracy: 0.8900
Epoch 30/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2715 - accuracy: 0.8900
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2690 - accuracy: 0.8916
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2668 - accuracy: 0.8905
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2665 - accuracy: 0.8945
Epoch 34/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2642 - accuracy: 0.8926
Epoch 35/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2630 - accuracy: 0.8911
Epoch 36/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2588 - accuracy: 0.8961
Epoch 37/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2564 - accuracy: 0.8943
Epoch 38/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2573 - accuracy: 0.8937
Epoch 39/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2559 - accuracy: 0.8967
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2536 - accuracy: 0.8963
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2534 - accuracy: 0.8960
Epoch 42/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2499 - accuracy: 0.8991
Epoch 43/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2489 - accuracy: 0.9008
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2478 - accuracy: 0.8986
Epoch 45/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2440 - accuracy: 0.9016
Epoch 46/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2430 - accuracy: 0.9036
Epoch 47/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2397 - accuracy: 0.9034
Epoch 48/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2380 - accuracy: 0.9046
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2363 - accuracy: 0.9068
Epoch 50/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2352 - accuracy: 0.9048
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4349 - accuracy: 0.8183
Epoch 2/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8536
Epoch 3/50
167/167 [==============================] - 0s 1ms/step - loss: 0.3452 - accuracy: 0.8592
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8635
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8622
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3252 - accuracy: 0.8684
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3203 - accuracy: 0.8706
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3152 - accuracy: 0.8704
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3139 - accuracy: 0.8727
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3095 - accuracy: 0.8753
Epoch 11/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3057 - accuracy: 0.8770
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3004 - accuracy: 0.8764
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2958 - accuracy: 0.8779
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2931 - accuracy: 0.8776
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2889 - accuracy: 0.8834
Epoch 16/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2859 - accuracy: 0.8807
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2827 - accuracy: 0.8783
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2780 - accuracy: 0.8815
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2757 - accuracy: 0.8862
Epoch 20/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2712 - accuracy: 0.8881
Epoch 21/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2712 - accuracy: 0.8851
Epoch 22/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2678 - accuracy: 0.8896
Epoch 23/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2639 - accuracy: 0.8897
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2589 - accuracy: 0.8920
Epoch 25/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2576 - accuracy: 0.8912
Epoch 26/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2529 - accuracy: 0.8879
Epoch 27/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2493 - accuracy: 0.8959
Epoch 28/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2468 - accuracy: 0.8969
Epoch 29/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2428 - accuracy: 0.9014
Epoch 30/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2418 - accuracy: 0.9004
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2409 - accuracy: 0.8978
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2333 - accuracy: 0.9027
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2325 - accuracy: 0.9010
Epoch 34/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2276 - accuracy: 0.9062
Epoch 35/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2233 - accuracy: 0.9064
Epoch 36/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2217 - accuracy: 0.9059
Epoch 37/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2193 - accuracy: 0.9083
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2133 - accuracy: 0.9106
Epoch 39/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2109 - accuracy: 0.9104
Epoch 40/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2074 - accuracy: 0.9139
Epoch 41/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2071 - accuracy: 0.9121
Epoch 42/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2031 - accuracy: 0.9171
Epoch 43/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1984 - accuracy: 0.9203
Epoch 44/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1975 - accuracy: 0.9177
Epoch 45/50
167/167 [==============================] - 0s 1ms/step - loss: 0.1940 - accuracy: 0.9171
Epoch 46/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1911 - accuracy: 0.9188
Epoch 47/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1862 - accuracy: 0.9244
Epoch 48/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1844 - accuracy: 0.9252
Epoch 49/50
167/167 [==============================] - 0s 1ms/step - loss: 0.1837 - accuracy: 0.9229
Epoch 50/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1793 - accuracy: 0.9242
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4381 - accuracy: 0.8041
Epoch 2/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3656 - accuracy: 0.8537
Epoch 3/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3450 - accuracy: 0.8566
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8605
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3286 - accuracy: 0.8661
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3267 - accuracy: 0.8682
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3212 - accuracy: 0.8669
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3160 - accuracy: 0.8687
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3129 - accuracy: 0.8699
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3064 - accuracy: 0.8721
Epoch 11/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3048 - accuracy: 0.8783
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3004 - accuracy: 0.8734
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2967 - accuracy: 0.8770
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2942 - accuracy: 0.8761
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2886 - accuracy: 0.8781
Epoch 16/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2856 - accuracy: 0.8806
Epoch 17/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2824 - accuracy: 0.8781
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2806 - accuracy: 0.8826
Epoch 19/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2733 - accuracy: 0.8849
Epoch 20/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2741 - accuracy: 0.8849
Epoch 21/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2708 - accuracy: 0.8897
Epoch 22/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2651 - accuracy: 0.8890
Epoch 23/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2624 - accuracy: 0.8879
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2569 - accuracy: 0.8916
Epoch 25/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2569 - accuracy: 0.8924
Epoch 26/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2527 - accuracy: 0.8929
Epoch 27/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2476 - accuracy: 0.8982
Epoch 28/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2476 - accuracy: 0.8965
Epoch 29/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2470 - accuracy: 0.8952
Epoch 30/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2397 - accuracy: 0.9002
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2376 - accuracy: 0.8976
Epoch 32/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2345 - accuracy: 0.8997
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2301 - accuracy: 0.9036
Epoch 34/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2265 - accuracy: 0.9059
Epoch 35/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2229 - accuracy: 0.9057
Epoch 36/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2206 - accuracy: 0.9092
Epoch 37/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2187 - accuracy: 0.9083
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2126 - accuracy: 0.9096
Epoch 39/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2129 - accuracy: 0.9092
Epoch 40/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2091 - accuracy: 0.9136
Epoch 41/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2025 - accuracy: 0.9136
Epoch 42/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2015 - accuracy: 0.9173
Epoch 43/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1971 - accuracy: 0.9209
Epoch 44/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1934 - accuracy: 0.9211
Epoch 45/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1919 - accuracy: 0.9220
Epoch 46/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1881 - accuracy: 0.9227
Epoch 47/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1889 - accuracy: 0.9209
Epoch 48/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1851 - accuracy: 0.9241
Epoch 49/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1804 - accuracy: 0.9297
Epoch 50/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1765 - accuracy: 0.9274
84/84 [==============================] - 0s 1ms/step
Epoch 1/50

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.4312 - accuracy: 0.8172
Epoch 2/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.8577
Epoch 3/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3352 - accuracy: 0.8645
Epoch 4/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8684
Epoch 5/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3232 - accuracy: 0.8695
Epoch 6/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3177 - accuracy: 0.8714
Epoch 7/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3132 - accuracy: 0.8755
Epoch 8/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3105 - accuracy: 0.8744
Epoch 9/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8727
Epoch 10/50
167/167 [==============================] - 0s 2ms/step - loss: 0.3027 - accuracy: 0.8800
Epoch 11/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2995 - accuracy: 0.8780
Epoch 12/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2958 - accuracy: 0.8802
Epoch 13/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2935 - accuracy: 0.8793
Epoch 14/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2894 - accuracy: 0.8840
Epoch 15/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2853 - accuracy: 0.8834
Epoch 16/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2832 - accuracy: 0.8851
Epoch 17/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2802 - accuracy: 0.8864
Epoch 18/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2747 - accuracy: 0.8885
Epoch 19/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2736 - accuracy: 0.8885
Epoch 20/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2705 - accuracy: 0.8894
Epoch 21/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2650 - accuracy: 0.8896
Epoch 22/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2629 - accuracy: 0.8937
Epoch 23/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2584 - accuracy: 0.8950
Epoch 24/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2555 - accuracy: 0.8995
Epoch 25/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2529 - accuracy: 0.8973
Epoch 26/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2508 - accuracy: 0.8975
Epoch 27/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2471 - accuracy: 0.9001
Epoch 28/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2415 - accuracy: 0.9019
Epoch 29/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2403 - accuracy: 0.8999
Epoch 30/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2372 - accuracy: 0.9063
Epoch 31/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2338 - accuracy: 0.9055
Epoch 32/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2290 - accuracy: 0.9072
Epoch 33/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2275 - accuracy: 0.9079
Epoch 34/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2218 - accuracy: 0.9123
Epoch 35/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2189 - accuracy: 0.9100
Epoch 36/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2182 - accuracy: 0.9117
Epoch 37/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2178 - accuracy: 0.9072
Epoch 38/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2088 - accuracy: 0.9164
Epoch 39/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2063 - accuracy: 0.9164
Epoch 40/50
167/167 [==============================] - 0s 1ms/step - loss: 0.2040 - accuracy: 0.9199
Epoch 41/50
167/167 [==============================] - 0s 2ms/step - loss: 0.2025 - accuracy: 0.9179
Epoch 42/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1951 - accuracy: 0.9216
Epoch 43/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1925 - accuracy: 0.9218
Epoch 44/50
167/167 [==============================] - 0s 1ms/step - loss: 0.1925 - accuracy: 0.9213
Epoch 45/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1878 - accuracy: 0.9231
Epoch 46/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1848 - accuracy: 0.9258
Epoch 47/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1824 - accuracy: 0.9271
Epoch 48/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1829 - accuracy: 0.9286
Epoch 49/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1756 - accuracy: 0.9304
Epoch 50/50
167/167 [==============================] - 0s 2ms/step - loss: 0.1736 - accuracy: 0.9269
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.5806 - accuracy: 0.7103
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4609 - accuracy: 0.8132
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4319 - accuracy: 0.8217
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4180 - accuracy: 0.8251
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4085 - accuracy: 0.8305
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3996 - accuracy: 0.8357
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3914 - accuracy: 0.8401
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3834 - accuracy: 0.8451
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3762 - accuracy: 0.8483
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3700 - accuracy: 0.8489
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3651 - accuracy: 0.8519
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3609 - accuracy: 0.8509
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3571 - accuracy: 0.8541
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3541 - accuracy: 0.8560
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3516 - accuracy: 0.8564
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8579
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3474 - accuracy: 0.8588
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3453 - accuracy: 0.8605
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3437 - accuracy: 0.8597
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3429 - accuracy: 0.8599
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3414 - accuracy: 0.8609
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3407 - accuracy: 0.8609
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3395 - accuracy: 0.8620
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3391 - accuracy: 0.8624
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8590
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3379 - accuracy: 0.8618
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8616
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3368 - accuracy: 0.8627
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8633
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8614
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.8622
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.8611
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8626
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8629
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8635
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8633
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8612
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8641
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8614
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8659
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8627
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8648
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8642
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8648
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8641
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8650
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8644
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8667
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8641
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8652
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8665
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8667
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8686
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8676
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8637
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8684
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3292 - accuracy: 0.8663
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8674
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8671
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8657
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8665
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8669
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8659
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8671
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8669
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8676
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8678
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8680
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8676
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3279 - accuracy: 0.8693
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8671
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8691
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3277 - accuracy: 0.8674
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3274 - accuracy: 0.8667
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3272 - accuracy: 0.8680
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8687
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8689
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8672
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8680
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8686
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8680
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8686
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8672
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8676
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8684
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8682
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8674
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3254 - accuracy: 0.8708
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8682
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8680
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8699
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3251 - accuracy: 0.8710
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8697
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8712
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3251 - accuracy: 0.8680
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8680
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8701
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8680
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8701
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8686
84/84 [==============================] - 0s 2ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.6134 - accuracy: 0.6555
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4722 - accuracy: 0.8011
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4400 - accuracy: 0.8101
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4245 - accuracy: 0.8151
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4131 - accuracy: 0.8191
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4027 - accuracy: 0.8226
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3930 - accuracy: 0.8294
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3834 - accuracy: 0.8371
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3760 - accuracy: 0.8404
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3694 - accuracy: 0.8453
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3644 - accuracy: 0.8462
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8476
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3567 - accuracy: 0.8532
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3539 - accuracy: 0.8522
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3514 - accuracy: 0.8539
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8558
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8567
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3469 - accuracy: 0.8566
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.8584
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3447 - accuracy: 0.8603
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8594
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3432 - accuracy: 0.8607
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3426 - accuracy: 0.8614
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8616
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3417 - accuracy: 0.8599
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3410 - accuracy: 0.8612
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3407 - accuracy: 0.8614
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8620
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8629
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3398 - accuracy: 0.8626
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3394 - accuracy: 0.8622
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3389 - accuracy: 0.8622
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8629
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8641
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8641
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8624
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8641
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8641
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3368 - accuracy: 0.8626
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8633
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3356 - accuracy: 0.8622
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8631
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8642
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8637
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8633
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8614
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8648
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8629
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8641
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8639
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8624
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8639
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8646
Epoch 54/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8629
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8624
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8633
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3318 - accuracy: 0.8639
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8650
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8646
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8641
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8657
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8633
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8641
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8657
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3306 - accuracy: 0.8627
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3299 - accuracy: 0.8650
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3295 - accuracy: 0.8637
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3299 - accuracy: 0.8656
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8669
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8648
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8650
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8657
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.8652
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8652
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8659
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3287 - accuracy: 0.8659
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8657
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3284 - accuracy: 0.8661
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3280 - accuracy: 0.8661
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3280 - accuracy: 0.8663
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3279 - accuracy: 0.8646
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3274 - accuracy: 0.8667
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3277 - accuracy: 0.8656
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3272 - accuracy: 0.8659
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8654
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8671
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8669
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3268 - accuracy: 0.8680
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3265 - accuracy: 0.8672
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3267 - accuracy: 0.8654
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3263 - accuracy: 0.8669
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3263 - accuracy: 0.8656
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8669
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8684
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8678
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8663
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8669
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8671
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8686
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8686
84/84 [==============================] - 0s 980us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5639 - accuracy: 0.7319
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4571 - accuracy: 0.8028
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4279 - accuracy: 0.8151
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4130 - accuracy: 0.8225
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4017 - accuracy: 0.8286
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3916 - accuracy: 0.8343
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3826 - accuracy: 0.8369
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3746 - accuracy: 0.8433
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3673 - accuracy: 0.8472
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3613 - accuracy: 0.8502
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3562 - accuracy: 0.8540
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3520 - accuracy: 0.8551
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3490 - accuracy: 0.8592
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3461 - accuracy: 0.8594
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3440 - accuracy: 0.8622
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3421 - accuracy: 0.8611
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3404 - accuracy: 0.8639
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8616
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8646
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8652
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8656
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8669
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8645
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8643
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8645
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8654
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8661
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3306 - accuracy: 0.8656
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8661
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8676
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8656
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8675
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8673
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8678
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3272 - accuracy: 0.8682
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8665
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8675
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8680
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8682
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8690
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8688
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8690
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8697
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8680
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8680
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8693
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8697
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8680
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8684
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8688
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8693
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8682
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3219 - accuracy: 0.8706
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8699
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3217 - accuracy: 0.8686
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8693
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8695
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8720
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8688
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8706
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8706
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8690
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8699
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3200 - accuracy: 0.8697
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8693
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8705
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8684
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8708
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8701
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8701
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3189 - accuracy: 0.8695
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8716
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3183 - accuracy: 0.8720
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8703
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8699
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8708
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8708
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8706
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8697
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3174 - accuracy: 0.8712
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8710
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8720
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8705
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8705
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3177 - accuracy: 0.8701
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8716
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8727
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3168 - accuracy: 0.8697
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8695
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8716
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8706
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8740
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8703
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8733
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8703
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8703
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3159 - accuracy: 0.8727
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8718
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3159 - accuracy: 0.8712
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8720
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.6227 - accuracy: 0.6441
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4439 - accuracy: 0.8117
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4183 - accuracy: 0.8222
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4058 - accuracy: 0.8290
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3962 - accuracy: 0.8386
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3880 - accuracy: 0.8406
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3809 - accuracy: 0.8461
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3738 - accuracy: 0.8491
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3673 - accuracy: 0.8506
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3617 - accuracy: 0.8519
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3565 - accuracy: 0.8552
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3525 - accuracy: 0.8562
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3495 - accuracy: 0.8592
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3462 - accuracy: 0.8590
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3437 - accuracy: 0.8603
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3416 - accuracy: 0.8614
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8620
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8605
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8627
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3362 - accuracy: 0.8627
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8659
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8637
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8637
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3318 - accuracy: 0.8650
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8669
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8652
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8657
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3297 - accuracy: 0.8624
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8669
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8656
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3279 - accuracy: 0.8646
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3274 - accuracy: 0.8661
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8669
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3265 - accuracy: 0.8663
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8672
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8644
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8689
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8676
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8669
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8663
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8672
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8686
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8693
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8697
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8672
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8676
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8684
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3216 - accuracy: 0.8699
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3215 - accuracy: 0.8697
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8686
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3207 - accuracy: 0.8684
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8704
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8686
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8704
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3198 - accuracy: 0.8704
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8680
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8691
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8691
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8725
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3183 - accuracy: 0.8701
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8702
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3186 - accuracy: 0.8680
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8706
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8710
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8702
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8693
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8723
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8702
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3168 - accuracy: 0.8702
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8704
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8723
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8674
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8719
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8710
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3161 - accuracy: 0.8723
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8734
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8717
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8672
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8723
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3150 - accuracy: 0.8702
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3150 - accuracy: 0.8736
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3147 - accuracy: 0.8717
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8710
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3142 - accuracy: 0.8729
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3148 - accuracy: 0.8719
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8732
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8716
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8736
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3135 - accuracy: 0.8727
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8710
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8712
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3132 - accuracy: 0.8721
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3130 - accuracy: 0.8710
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8731
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8732
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8734
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8719
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8740
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8727
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8742
84/84 [==============================] - 0s 967us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7377
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4318 - accuracy: 0.8123
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4141 - accuracy: 0.8200
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4022 - accuracy: 0.8241
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3913 - accuracy: 0.8329
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3812 - accuracy: 0.8401
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3722 - accuracy: 0.8466
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3648 - accuracy: 0.8502
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3593 - accuracy: 0.8536
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3549 - accuracy: 0.8522
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3513 - accuracy: 0.8552
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3477 - accuracy: 0.8569
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3461 - accuracy: 0.8577
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3442 - accuracy: 0.8590
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3421 - accuracy: 0.8590
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3410 - accuracy: 0.8609
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3396 - accuracy: 0.8597
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8605
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3381 - accuracy: 0.8614
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8612
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8624
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8607
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.8611
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8633
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8627
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8622
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8627
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8627
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8611
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8646
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3316 - accuracy: 0.8611
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8641
Epoch 33/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8644
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 0.8639
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8635
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8633
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8652
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3295 - accuracy: 0.8642
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3287 - accuracy: 0.8627
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3283 - accuracy: 0.8652
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8650
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8642
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3277 - accuracy: 0.8629
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8671
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8650
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3267 - accuracy: 0.8654
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8663
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3260 - accuracy: 0.8659
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8678
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3258 - accuracy: 0.8684
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3254 - accuracy: 0.8652
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8687
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3244 - accuracy: 0.8680
Epoch 54/100
167/167 [==============================] - 1s 3ms/step - loss: 0.3246 - accuracy: 0.8687
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3241 - accuracy: 0.8654
Epoch 56/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3236 - accuracy: 0.8682
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3240 - accuracy: 0.8676
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.8663
Epoch 59/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8671
Epoch 60/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3224 - accuracy: 0.8684
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3226 - accuracy: 0.8665
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.8689
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.8704
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3218 - accuracy: 0.8697
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3215 - accuracy: 0.8676
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3211 - accuracy: 0.8695
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3208 - accuracy: 0.8689
Epoch 68/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3208 - accuracy: 0.8702
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3203 - accuracy: 0.8684
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3200 - accuracy: 0.8725
Epoch 71/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3200 - accuracy: 0.8693
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3205 - accuracy: 0.8665
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3198 - accuracy: 0.8714
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3197 - accuracy: 0.8697
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3190 - accuracy: 0.8701
Epoch 76/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3193 - accuracy: 0.8687
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3188 - accuracy: 0.8701
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8701
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3186 - accuracy: 0.8708
Epoch 80/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3181 - accuracy: 0.8699
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3180 - accuracy: 0.8701
Epoch 82/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3176 - accuracy: 0.8725
Epoch 83/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3178 - accuracy: 0.8701
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3177 - accuracy: 0.8701
Epoch 85/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3174 - accuracy: 0.8716
Epoch 86/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3175 - accuracy: 0.8697
Epoch 87/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3169 - accuracy: 0.8721
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3173 - accuracy: 0.8708
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3168 - accuracy: 0.8727
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3163 - accuracy: 0.8725
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8710
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3159 - accuracy: 0.8729
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3161 - accuracy: 0.8736
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3161 - accuracy: 0.8716
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3160 - accuracy: 0.8723
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8725
Epoch 97/100
167/167 [==============================] - 0s 958us/step - loss: 0.3153 - accuracy: 0.8710
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8714
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3151 - accuracy: 0.8732
Epoch 100/100
167/167 [==============================] - 0s 972us/step - loss: 0.3149 - accuracy: 0.8714
84/84 [==============================] - 0s 664us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 919us/step - loss: 0.5164 - accuracy: 0.7715
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4328 - accuracy: 0.8073
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4135 - accuracy: 0.8174
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4006 - accuracy: 0.8262
Epoch 5/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3896 - accuracy: 0.8360
Epoch 6/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3794 - accuracy: 0.8425
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3704 - accuracy: 0.8474
Epoch 8/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8525
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3562 - accuracy: 0.8547
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8566
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8562
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3432 - accuracy: 0.8603
Epoch 13/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3410 - accuracy: 0.8618
Epoch 14/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8630
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 0.8637
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8650
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8637
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8660
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8658
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8691
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8680
Epoch 22/100
167/167 [==============================] - 0s 975us/step - loss: 0.3294 - accuracy: 0.8690
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8690
Epoch 24/100
167/167 [==============================] - 0s 999us/step - loss: 0.3285 - accuracy: 0.8684
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3280 - accuracy: 0.8678
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3272 - accuracy: 0.8680
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8703
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8714
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8695
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8706
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8699
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3241 - accuracy: 0.8705
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8720
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3238 - accuracy: 0.8718
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8735
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3225 - accuracy: 0.8720
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8736
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8718
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3216 - accuracy: 0.8731
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8705
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8723
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8712
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8736
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8733
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3200 - accuracy: 0.8723
Epoch 46/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3191 - accuracy: 0.8738
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3183 - accuracy: 0.8714
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8736
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8733
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8731
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8738
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8738
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8742
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8748
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3156 - accuracy: 0.8735
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8763
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8735
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3147 - accuracy: 0.8761
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8757
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8748
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8748
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8744
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8766
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8755
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8761
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8720
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8750
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8750
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3112 - accuracy: 0.8761
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3111 - accuracy: 0.8755
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8759
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8761
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8766
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3098 - accuracy: 0.8778
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3101 - accuracy: 0.8781
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3093 - accuracy: 0.8780
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8780
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8742
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3084 - accuracy: 0.8768
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3086 - accuracy: 0.8753
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.8780
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3079 - accuracy: 0.8768
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8778
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3079 - accuracy: 0.8780
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.8781
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8772
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3074 - accuracy: 0.8763
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8757
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8753
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3065 - accuracy: 0.8753
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8757
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8763
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8770
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3055 - accuracy: 0.8778
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3051 - accuracy: 0.8778
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3054 - accuracy: 0.8770
Epoch 97/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3046 - accuracy: 0.8796
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3045 - accuracy: 0.8776
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8759
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3043 - accuracy: 0.8776
84/84 [==============================] - 0s 863us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4947 - accuracy: 0.7928
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4175 - accuracy: 0.8224
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3968 - accuracy: 0.8359
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3805 - accuracy: 0.8442
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3677 - accuracy: 0.8517
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3580 - accuracy: 0.8552
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3512 - accuracy: 0.8562
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3468 - accuracy: 0.8588
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3436 - accuracy: 0.8596
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3418 - accuracy: 0.8618
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3394 - accuracy: 0.8620
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8637
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8642
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8644
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8639
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8633
Epoch 17/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8654
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8641
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3302 - accuracy: 0.8641
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8629
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8657
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8642
Epoch 23/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3280 - accuracy: 0.8650
Epoch 24/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8657
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8642
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3268 - accuracy: 0.8674
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3251 - accuracy: 0.8639
Epoch 28/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3239 - accuracy: 0.8671
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3250 - accuracy: 0.8654
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3235 - accuracy: 0.8646
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3231 - accuracy: 0.8665
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3228 - accuracy: 0.8665
Epoch 33/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3220 - accuracy: 0.8671
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3218 - accuracy: 0.8672
Epoch 35/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3213 - accuracy: 0.8693
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3206 - accuracy: 0.8695
Epoch 37/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3208 - accuracy: 0.8672
Epoch 38/100
167/167 [==============================] - 0s 3ms/step - loss: 0.3196 - accuracy: 0.8704
Epoch 39/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3200 - accuracy: 0.8695
Epoch 40/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3190 - accuracy: 0.8708
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8691
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3189 - accuracy: 0.8682
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8697
Epoch 44/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3179 - accuracy: 0.8717
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3175 - accuracy: 0.8691
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3170 - accuracy: 0.8676
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8732
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8691
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8693
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8714
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8710
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8734
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3138 - accuracy: 0.8725
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3140 - accuracy: 0.8719
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3135 - accuracy: 0.8734
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3138 - accuracy: 0.8689
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8742
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3117 - accuracy: 0.8734
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8742
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3123 - accuracy: 0.8719
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8716
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3114 - accuracy: 0.8757
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3110 - accuracy: 0.8712
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8746
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8738
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8740
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8731
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3083 - accuracy: 0.8746
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3082 - accuracy: 0.8732
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8736
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3082 - accuracy: 0.8749
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.8731
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3080 - accuracy: 0.8736
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.8757
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8723
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8757
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3054 - accuracy: 0.8770
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3049 - accuracy: 0.8734
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3053 - accuracy: 0.8776
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3043 - accuracy: 0.8744
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8781
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8734
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8749
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8731
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8766
Epoch 86/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3026 - accuracy: 0.8759
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8792
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3014 - accuracy: 0.8802
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8751
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3006 - accuracy: 0.8779
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3000 - accuracy: 0.8762
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3002 - accuracy: 0.8766
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3005 - accuracy: 0.8777
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8789
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8779
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8772
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2990 - accuracy: 0.8776
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2976 - accuracy: 0.8787
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2982 - accuracy: 0.8792
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8766
84/84 [==============================] - 0s 919us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4819 - accuracy: 0.7838
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4142 - accuracy: 0.8189
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3964 - accuracy: 0.8294
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3798 - accuracy: 0.8406
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3667 - accuracy: 0.8511
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3580 - accuracy: 0.8539
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3511 - accuracy: 0.8586
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3461 - accuracy: 0.8582
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3436 - accuracy: 0.8605
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3411 - accuracy: 0.8603
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3385 - accuracy: 0.8605
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8618
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8622
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8633
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8629
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8644
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3318 - accuracy: 0.8641
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8627
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8642
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8620
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8661
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8676
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8656
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8656
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3265 - accuracy: 0.8656
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3254 - accuracy: 0.8654
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8635
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8682
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8689
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.8661
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8697
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8659
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8678
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8671
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3218 - accuracy: 0.8661
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8676
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8676
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8674
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8669
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3195 - accuracy: 0.8693
Epoch 41/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3183 - accuracy: 0.8706
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8674
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8704
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8684
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3166 - accuracy: 0.8684
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8695
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8684
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8701
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3159 - accuracy: 0.8699
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8689
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3153 - accuracy: 0.8697
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3142 - accuracy: 0.8701
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3146 - accuracy: 0.8729
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3143 - accuracy: 0.8686
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8697
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3134 - accuracy: 0.8717
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8701
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3120 - accuracy: 0.8697
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8691
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3112 - accuracy: 0.8723
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3116 - accuracy: 0.8740
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8727
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3101 - accuracy: 0.8714
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8714
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8731
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3082 - accuracy: 0.8719
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8734
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8732
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3070 - accuracy: 0.8751
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3054 - accuracy: 0.8749
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3049 - accuracy: 0.8740
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8729
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3047 - accuracy: 0.8757
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8768
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8770
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8759
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3030 - accuracy: 0.8747
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3028 - accuracy: 0.8751
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8766
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8761
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3014 - accuracy: 0.8761
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8776
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3015 - accuracy: 0.8768
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8762
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8791
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8776
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2994 - accuracy: 0.8807
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8777
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2981 - accuracy: 0.8779
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.8777
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2971 - accuracy: 0.8800
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2979 - accuracy: 0.8777
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8777
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2971 - accuracy: 0.8800
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2966 - accuracy: 0.8768
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2964 - accuracy: 0.8783
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2960 - accuracy: 0.8789
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2957 - accuracy: 0.8781
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2952 - accuracy: 0.8796
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2949 - accuracy: 0.8785
84/84 [==============================] - 0s 854us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4586 - accuracy: 0.7983
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4138 - accuracy: 0.8243
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8348
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3837 - accuracy: 0.8408
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3701 - accuracy: 0.8502
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8556
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.8588
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3439 - accuracy: 0.8628
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3397 - accuracy: 0.8637
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8652
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8680
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8661
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8669
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8691
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8669
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8682
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3272 - accuracy: 0.8680
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8703
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3249 - accuracy: 0.8699
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.8686
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8693
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8680
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8714
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8706
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3201 - accuracy: 0.8733
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3202 - accuracy: 0.8701
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8733
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8718
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8718
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3171 - accuracy: 0.8733
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8714
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8744
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8735
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8712
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8735
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3146 - accuracy: 0.8712
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8729
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3143 - accuracy: 0.8708
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8742
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3132 - accuracy: 0.8716
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8744
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3125 - accuracy: 0.8731
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8744
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8742
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3104 - accuracy: 0.8761
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3103 - accuracy: 0.8755
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8761
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8751
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8759
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3083 - accuracy: 0.8753
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8750
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8742
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.8755
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3070 - accuracy: 0.8751
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8763
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3062 - accuracy: 0.8759
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8768
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3051 - accuracy: 0.8765
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3055 - accuracy: 0.8757
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3048 - accuracy: 0.8759
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3047 - accuracy: 0.8751
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8751
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3037 - accuracy: 0.8765
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8757
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8774
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8770
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8761
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3011 - accuracy: 0.8787
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3021 - accuracy: 0.8793
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3007 - accuracy: 0.8778
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3005 - accuracy: 0.8798
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8761
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.8783
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8813
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8781
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.8774
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2985 - accuracy: 0.8785
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2981 - accuracy: 0.8781
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2979 - accuracy: 0.8785
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8795
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.8780
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8789
Epoch 83/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2965 - accuracy: 0.8781
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2961 - accuracy: 0.8800
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8800
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2950 - accuracy: 0.8806
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2945 - accuracy: 0.8795
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2955 - accuracy: 0.8793
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2945 - accuracy: 0.8793
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2943 - accuracy: 0.8808
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2937 - accuracy: 0.8804
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2931 - accuracy: 0.8804
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2934 - accuracy: 0.8815
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8802
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2923 - accuracy: 0.8798
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2916 - accuracy: 0.8817
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2926 - accuracy: 0.8819
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2923 - accuracy: 0.8798
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2908 - accuracy: 0.8823
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2903 - accuracy: 0.8828
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4622 - accuracy: 0.8057
Epoch 2/100
167/167 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8288
Epoch 3/100
167/167 [==============================] - 1s 3ms/step - loss: 0.3838 - accuracy: 0.8440
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3668 - accuracy: 0.8556
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3553 - accuracy: 0.8590
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3488 - accuracy: 0.8614
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3434 - accuracy: 0.8642
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8633
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8627
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3366 - accuracy: 0.8652
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8635
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8637
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8631
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8667
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8656
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3274 - accuracy: 0.8642
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8652
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3262 - accuracy: 0.8654
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8659
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8641
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8689
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8674
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3216 - accuracy: 0.8701
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8680
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8702
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3206 - accuracy: 0.8699
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8695
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8706
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8704
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8693
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3179 - accuracy: 0.8716
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3182 - accuracy: 0.8693
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8706
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8725
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8729
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8712
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8704
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8732
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8717
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3123 - accuracy: 0.8738
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3119 - accuracy: 0.8731
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8742
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3110 - accuracy: 0.8725
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8749
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3098 - accuracy: 0.8736
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8740
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3081 - accuracy: 0.8742
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3077 - accuracy: 0.8742
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8762
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3062 - accuracy: 0.8744
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8749
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8757
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8749
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8755
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3036 - accuracy: 0.8768
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8738
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8783
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3008 - accuracy: 0.8777
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8774
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3017 - accuracy: 0.8749
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2998 - accuracy: 0.8792
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3007 - accuracy: 0.8747
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8787
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2976 - accuracy: 0.8772
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2977 - accuracy: 0.8804
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2966 - accuracy: 0.8802
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2963 - accuracy: 0.8783
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2955 - accuracy: 0.8776
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8792
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2963 - accuracy: 0.8792
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2950 - accuracy: 0.8785
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8789
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2934 - accuracy: 0.8794
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8821
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2928 - accuracy: 0.8811
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2921 - accuracy: 0.8839
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2908 - accuracy: 0.8792
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2911 - accuracy: 0.8817
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2906 - accuracy: 0.8806
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8809
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2881 - accuracy: 0.8832
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2883 - accuracy: 0.8837
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2884 - accuracy: 0.8789
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2871 - accuracy: 0.8811
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2888 - accuracy: 0.8804
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2876 - accuracy: 0.8843
Epoch 87/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2856 - accuracy: 0.8847
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2846 - accuracy: 0.8821
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2851 - accuracy: 0.8852
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2839 - accuracy: 0.8839
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2849 - accuracy: 0.8841
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2829 - accuracy: 0.8830
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2825 - accuracy: 0.8834
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2823 - accuracy: 0.8830
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2815 - accuracy: 0.8854
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2822 - accuracy: 0.8862
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2806 - accuracy: 0.8839
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2801 - accuracy: 0.8851
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2796 - accuracy: 0.8873
Epoch 100/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2800 - accuracy: 0.8845
84/84 [==============================] - 0s 952us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4705 - accuracy: 0.7994
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4073 - accuracy: 0.8254
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3839 - accuracy: 0.8436
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3678 - accuracy: 0.8496
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3556 - accuracy: 0.8549
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3485 - accuracy: 0.8586
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3440 - accuracy: 0.8605
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3406 - accuracy: 0.8609
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8631
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8599
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8629
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8657
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8637
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8633
Epoch 15/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8671
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3306 - accuracy: 0.8661
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8656
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8665
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8661
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8667
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8663
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8682
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8684
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8687
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8663
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8663
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8669
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8693
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3224 - accuracy: 0.8680
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8697
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8686
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8701
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8751
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8691
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3180 - accuracy: 0.8710
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8736
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3169 - accuracy: 0.8714
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3156 - accuracy: 0.8732
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8697
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8699
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3131 - accuracy: 0.8716
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3131 - accuracy: 0.8712
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3121 - accuracy: 0.8729
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3114 - accuracy: 0.8736
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3097 - accuracy: 0.8723
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8744
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3101 - accuracy: 0.8719
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8736
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.8764
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3077 - accuracy: 0.8744
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8734
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8768
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8732
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3037 - accuracy: 0.8798
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3042 - accuracy: 0.8764
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8751
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3024 - accuracy: 0.8779
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3017 - accuracy: 0.8783
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8777
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8764
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2993 - accuracy: 0.8787
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3002 - accuracy: 0.8774
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2985 - accuracy: 0.8781
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2985 - accuracy: 0.8779
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2977 - accuracy: 0.8781
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2971 - accuracy: 0.8772
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8781
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2970 - accuracy: 0.8794
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2959 - accuracy: 0.8800
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2951 - accuracy: 0.8783
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8777
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2946 - accuracy: 0.8813
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2934 - accuracy: 0.8800
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2933 - accuracy: 0.8811
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2930 - accuracy: 0.8819
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2917 - accuracy: 0.8785
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2919 - accuracy: 0.8807
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2903 - accuracy: 0.8800
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2911 - accuracy: 0.8830
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2903 - accuracy: 0.8806
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2891 - accuracy: 0.8834
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2893 - accuracy: 0.8809
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8802
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2881 - accuracy: 0.8822
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2874 - accuracy: 0.8851
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2874 - accuracy: 0.8822
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2877 - accuracy: 0.8826
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2858 - accuracy: 0.8822
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2849 - accuracy: 0.8828
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8828
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2850 - accuracy: 0.8843
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2842 - accuracy: 0.8826
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8839
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2827 - accuracy: 0.8832
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2823 - accuracy: 0.8843
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2830 - accuracy: 0.8851
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2820 - accuracy: 0.8849
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2821 - accuracy: 0.8828
Epoch 99/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2811 - accuracy: 0.8828
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2806 - accuracy: 0.8828
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4504 - accuracy: 0.8090
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3965 - accuracy: 0.8328
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3742 - accuracy: 0.8500
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3556 - accuracy: 0.8605
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3467 - accuracy: 0.8594
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3403 - accuracy: 0.8646
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8641
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8645
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8680
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8669
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3282 - accuracy: 0.8699
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8697
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3241 - accuracy: 0.8703
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8693
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8680
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8714
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3219 - accuracy: 0.8703
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8705
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8723
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3183 - accuracy: 0.8705
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8693
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8706
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8729
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8712
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3138 - accuracy: 0.8714
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3138 - accuracy: 0.8736
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3134 - accuracy: 0.8710
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8733
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3112 - accuracy: 0.8714
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3105 - accuracy: 0.8731
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3104 - accuracy: 0.8750
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3083 - accuracy: 0.8755
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8751
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8738
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8772
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8753
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8735
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8765
Epoch 39/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3051 - accuracy: 0.8755
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8759
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8770
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3018 - accuracy: 0.8770
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8783
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8785
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8744
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8787
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2981 - accuracy: 0.8774
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8774
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8793
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2964 - accuracy: 0.8795
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 0.8793
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2966 - accuracy: 0.8787
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2941 - accuracy: 0.8800
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2937 - accuracy: 0.8785
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2938 - accuracy: 0.8800
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2936 - accuracy: 0.8811
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2924 - accuracy: 0.8800
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2913 - accuracy: 0.8828
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2907 - accuracy: 0.8806
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2907 - accuracy: 0.8795
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8785
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2900 - accuracy: 0.8819
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2882 - accuracy: 0.8817
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2878 - accuracy: 0.8813
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2872 - accuracy: 0.8819
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2866 - accuracy: 0.8828
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2865 - accuracy: 0.8841
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2853 - accuracy: 0.8828
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2864 - accuracy: 0.8841
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2858 - accuracy: 0.8819
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8834
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2853 - accuracy: 0.8843
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2836 - accuracy: 0.8821
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2838 - accuracy: 0.8841
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2829 - accuracy: 0.8840
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2821 - accuracy: 0.8838
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2807 - accuracy: 0.8847
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2815 - accuracy: 0.8886
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2803 - accuracy: 0.8864
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2808 - accuracy: 0.8879
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2779 - accuracy: 0.8856
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2795 - accuracy: 0.8881
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2789 - accuracy: 0.8855
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2786 - accuracy: 0.8903
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2777 - accuracy: 0.8877
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2787 - accuracy: 0.8888
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2783 - accuracy: 0.8900
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.8856
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2754 - accuracy: 0.8886
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2754 - accuracy: 0.8907
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2754 - accuracy: 0.8875
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2753 - accuracy: 0.8871
Epoch 93/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2738 - accuracy: 0.8898
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2740 - accuracy: 0.8877
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2743 - accuracy: 0.8909
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2725 - accuracy: 0.8920
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2724 - accuracy: 0.8928
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2728 - accuracy: 0.8898
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2726 - accuracy: 0.8907
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2710 - accuracy: 0.8901
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7553
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4412 - accuracy: 0.8089
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4181 - accuracy: 0.8164
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4046 - accuracy: 0.8262
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3893 - accuracy: 0.8389
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3748 - accuracy: 0.8498
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 0.8524
Epoch 8/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8581
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8614
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3479 - accuracy: 0.8611
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3441 - accuracy: 0.8611
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3418 - accuracy: 0.8659
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3395 - accuracy: 0.8637
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3381 - accuracy: 0.8657
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3356 - accuracy: 0.8669
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8659
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8669
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8669
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8657
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8674
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3285 - accuracy: 0.8682
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8669
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8712
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8661
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8672
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8684
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8686
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8689
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3218 - accuracy: 0.8697
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8684
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8701
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8701
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3190 - accuracy: 0.8680
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3189 - accuracy: 0.8695
Epoch 35/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3182 - accuracy: 0.8701
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3170 - accuracy: 0.8699
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8717
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3164 - accuracy: 0.8710
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8716
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3154 - accuracy: 0.8721
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8701
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8719
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8731
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3132 - accuracy: 0.8714
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8717
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3125 - accuracy: 0.8695
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8727
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3124 - accuracy: 0.8712
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8712
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3118 - accuracy: 0.8706
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3110 - accuracy: 0.8717
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3107 - accuracy: 0.8716
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.8723
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8727
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3092 - accuracy: 0.8706
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8712
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8740
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3092 - accuracy: 0.8729
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3082 - accuracy: 0.8729
Epoch 60/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3078 - accuracy: 0.8731
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3077 - accuracy: 0.8734
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3082 - accuracy: 0.8736
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8729
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3066 - accuracy: 0.8721
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8723
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3067 - accuracy: 0.8740
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3054 - accuracy: 0.8731
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3060 - accuracy: 0.8740
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8734
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8744
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3053 - accuracy: 0.8736
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8755
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8753
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8736
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3036 - accuracy: 0.8744
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3030 - accuracy: 0.8774
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8740
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8755
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3028 - accuracy: 0.8757
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8751
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3017 - accuracy: 0.8757
Epoch 82/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3019 - accuracy: 0.8774
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8761
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8753
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3011 - accuracy: 0.8781
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3006 - accuracy: 0.8738
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3007 - accuracy: 0.8753
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8768
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3006 - accuracy: 0.8742
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3003 - accuracy: 0.8759
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8776
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8770
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2993 - accuracy: 0.8781
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2986 - accuracy: 0.8796
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8776
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2997 - accuracy: 0.8770
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2980 - accuracy: 0.8757
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2988 - accuracy: 0.8753
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2984 - accuracy: 0.8779
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2981 - accuracy: 0.8766
84/84 [==============================] - 0s 985us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5176 - accuracy: 0.7705
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.8039
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4206 - accuracy: 0.8149
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4034 - accuracy: 0.8192
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3874 - accuracy: 0.8316
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3713 - accuracy: 0.8459
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3586 - accuracy: 0.8504
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3501 - accuracy: 0.8554
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3441 - accuracy: 0.8588
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3410 - accuracy: 0.8581
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8614
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8594
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8624
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8614
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8626
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8642
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8648
Epoch 18/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3276 - accuracy: 0.8661
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3271 - accuracy: 0.8637
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3255 - accuracy: 0.8661
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8682
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3242 - accuracy: 0.8676
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8663
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8672
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8654
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3205 - accuracy: 0.8656
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3202 - accuracy: 0.8663
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3200 - accuracy: 0.8652
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3188 - accuracy: 0.8682
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3184 - accuracy: 0.8659
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3181 - accuracy: 0.8686
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8697
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3168 - accuracy: 0.8714
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8693
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8678
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3158 - accuracy: 0.8657
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3149 - accuracy: 0.8702
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8706
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8697
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3136 - accuracy: 0.8701
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3135 - accuracy: 0.8699
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3125 - accuracy: 0.8708
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3125 - accuracy: 0.8689
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3117 - accuracy: 0.8699
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3112 - accuracy: 0.8706
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8699
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8706
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3105 - accuracy: 0.8716
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3104 - accuracy: 0.8712
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3092 - accuracy: 0.8706
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8706
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8699
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8693
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8708
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3087 - accuracy: 0.8699
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8701
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3073 - accuracy: 0.8727
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8701
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8704
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8723
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8706
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8721
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8721
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8742
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3049 - accuracy: 0.8693
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8717
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3045 - accuracy: 0.8717
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8734
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3042 - accuracy: 0.8729
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8717
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8723
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3033 - accuracy: 0.8729
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.8717
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3031 - accuracy: 0.8727
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3020 - accuracy: 0.8706
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3022 - accuracy: 0.8744
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3024 - accuracy: 0.8742
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3017 - accuracy: 0.8717
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3007 - accuracy: 0.8747
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3012 - accuracy: 0.8734
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3002 - accuracy: 0.8723
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8744
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3019 - accuracy: 0.8727
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8732
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2999 - accuracy: 0.8731
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8736
Epoch 87/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3005 - accuracy: 0.8721
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2997 - accuracy: 0.8746
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2997 - accuracy: 0.8732
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8749
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2991 - accuracy: 0.8734
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2988 - accuracy: 0.8744
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2989 - accuracy: 0.8751
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.8729
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2985 - accuracy: 0.8753
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2983 - accuracy: 0.8738
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8747
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.8725
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8740
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2977 - accuracy: 0.8751
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7683
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4386 - accuracy: 0.8148
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4153 - accuracy: 0.8202
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4011 - accuracy: 0.8301
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3877 - accuracy: 0.8420
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3741 - accuracy: 0.8480
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3619 - accuracy: 0.8536
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3518 - accuracy: 0.8583
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3451 - accuracy: 0.8607
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8637
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8645
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3344 - accuracy: 0.8673
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8656
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8675
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8680
Epoch 16/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8678
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3275 - accuracy: 0.8673
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8695
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8720
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8693
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8718
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8718
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8705
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3206 - accuracy: 0.8705
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8708
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8706
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8716
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3180 - accuracy: 0.8727
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3187 - accuracy: 0.8708
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3175 - accuracy: 0.8721
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8729
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3161 - accuracy: 0.8721
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3146 - accuracy: 0.8735
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8748
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3140 - accuracy: 0.8738
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3143 - accuracy: 0.8751
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3127 - accuracy: 0.8765
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8751
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3120 - accuracy: 0.8746
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3119 - accuracy: 0.8765
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3114 - accuracy: 0.8735
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3111 - accuracy: 0.8746
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3105 - accuracy: 0.8744
Epoch 44/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.8750
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8755
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8766
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8778
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8768
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8757
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.8751
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.8768
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.8766
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8776
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8772
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3061 - accuracy: 0.8753
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8766
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3053 - accuracy: 0.8783
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3053 - accuracy: 0.8774
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3052 - accuracy: 0.8793
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3050 - accuracy: 0.8770
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8778
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8768
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8776
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8778
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3032 - accuracy: 0.8780
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3030 - accuracy: 0.8783
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3031 - accuracy: 0.8780
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8774
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8778
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8772
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8798
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3017 - accuracy: 0.8804
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3011 - accuracy: 0.8774
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3021 - accuracy: 0.8796
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.8793
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3002 - accuracy: 0.8804
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8789
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3007 - accuracy: 0.8781
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3004 - accuracy: 0.8778
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8815
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.8821
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8819
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2994 - accuracy: 0.8813
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2985 - accuracy: 0.8804
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2992 - accuracy: 0.8838
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.8830
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2988 - accuracy: 0.8806
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8819
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8823
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2979 - accuracy: 0.8819
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2980 - accuracy: 0.8825
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8832
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2967 - accuracy: 0.8819
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8815
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8826
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2962 - accuracy: 0.8840
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2963 - accuracy: 0.8845
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2959 - accuracy: 0.8808
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 0.8817
Epoch 100/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2953 - accuracy: 0.8849
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.5041 - accuracy: 0.7611
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8224
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 0.8401
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3677 - accuracy: 0.8507
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3529 - accuracy: 0.8547
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3441 - accuracy: 0.8618
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8599
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8624
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8633
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8684
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3264 - accuracy: 0.8616
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3244 - accuracy: 0.8657
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3227 - accuracy: 0.8659
Epoch 14/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3206 - accuracy: 0.8687
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8680
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8689
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8699
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3147 - accuracy: 0.8704
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8702
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8702
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3100 - accuracy: 0.8727
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8736
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3085 - accuracy: 0.8702
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8719
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3051 - accuracy: 0.8729
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3044 - accuracy: 0.8736
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3031 - accuracy: 0.8742
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3018 - accuracy: 0.8777
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2998 - accuracy: 0.8740
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2993 - accuracy: 0.8729
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2970 - accuracy: 0.8753
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2975 - accuracy: 0.8755
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2960 - accuracy: 0.8785
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2959 - accuracy: 0.8753
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2936 - accuracy: 0.8796
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2928 - accuracy: 0.8776
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2927 - accuracy: 0.8785
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2923 - accuracy: 0.8779
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2909 - accuracy: 0.8791
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2896 - accuracy: 0.8772
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2894 - accuracy: 0.8791
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2885 - accuracy: 0.8817
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2900 - accuracy: 0.8772
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2869 - accuracy: 0.8796
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2877 - accuracy: 0.8802
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2848 - accuracy: 0.8796
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2845 - accuracy: 0.8813
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2831 - accuracy: 0.8811
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2842 - accuracy: 0.8811
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2825 - accuracy: 0.8832
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2812 - accuracy: 0.8828
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2810 - accuracy: 0.8841
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2796 - accuracy: 0.8847
Epoch 54/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2802 - accuracy: 0.8834
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2781 - accuracy: 0.8836
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2781 - accuracy: 0.8839
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2773 - accuracy: 0.8819
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.8858
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2752 - accuracy: 0.8839
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2742 - accuracy: 0.8864
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2745 - accuracy: 0.8879
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2747 - accuracy: 0.8845
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2715 - accuracy: 0.8860
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2714 - accuracy: 0.8852
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2726 - accuracy: 0.8875
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2713 - accuracy: 0.8869
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2690 - accuracy: 0.8882
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2706 - accuracy: 0.8849
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2674 - accuracy: 0.8892
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2690 - accuracy: 0.8881
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2679 - accuracy: 0.8912
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2664 - accuracy: 0.8867
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2676 - accuracy: 0.8873
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2660 - accuracy: 0.8899
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2654 - accuracy: 0.8909
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2648 - accuracy: 0.8912
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2643 - accuracy: 0.8916
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2633 - accuracy: 0.8927
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2617 - accuracy: 0.8926
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2626 - accuracy: 0.8929
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2613 - accuracy: 0.8914
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2616 - accuracy: 0.8914
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2605 - accuracy: 0.8937
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2616 - accuracy: 0.8907
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2588 - accuracy: 0.8933
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2596 - accuracy: 0.8911
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2565 - accuracy: 0.8911
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2575 - accuracy: 0.8912
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2569 - accuracy: 0.8969
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2555 - accuracy: 0.8944
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2554 - accuracy: 0.8957
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2545 - accuracy: 0.8957
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2554 - accuracy: 0.8918
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2529 - accuracy: 0.8946
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2534 - accuracy: 0.8976
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2539 - accuracy: 0.8959
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2534 - accuracy: 0.8957
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2505 - accuracy: 0.8957
Epoch 99/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2505 - accuracy: 0.8957
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2498 - accuracy: 0.8952
84/84 [==============================] - 0s 981us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4932 - accuracy: 0.7815
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4199 - accuracy: 0.8209
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3976 - accuracy: 0.8331
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3775 - accuracy: 0.8447
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3603 - accuracy: 0.8528
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3500 - accuracy: 0.8551
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3449 - accuracy: 0.8564
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3399 - accuracy: 0.8594
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8618
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8639
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3320 - accuracy: 0.8631
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8641
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8642
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8661
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3234 - accuracy: 0.8667
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3213 - accuracy: 0.8676
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3192 - accuracy: 0.8678
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3167 - accuracy: 0.8697
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3163 - accuracy: 0.8697
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8731
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3128 - accuracy: 0.8699
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3113 - accuracy: 0.8719
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8736
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.8721
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3075 - accuracy: 0.8706
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3060 - accuracy: 0.8732
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8725
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3035 - accuracy: 0.8744
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3018 - accuracy: 0.8738
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8716
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3000 - accuracy: 0.8764
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2976 - accuracy: 0.8768
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2979 - accuracy: 0.8759
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2967 - accuracy: 0.8761
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2967 - accuracy: 0.8772
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8761
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2942 - accuracy: 0.8766
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2930 - accuracy: 0.8783
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2928 - accuracy: 0.8747
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2912 - accuracy: 0.8768
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2900 - accuracy: 0.8762
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2888 - accuracy: 0.8766
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2884 - accuracy: 0.8776
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2887 - accuracy: 0.8774
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2864 - accuracy: 0.8819
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2866 - accuracy: 0.8791
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2856 - accuracy: 0.8774
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2837 - accuracy: 0.8841
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2853 - accuracy: 0.8776
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2841 - accuracy: 0.8791
Epoch 51/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2818 - accuracy: 0.8796
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2823 - accuracy: 0.8807
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2799 - accuracy: 0.8819
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2807 - accuracy: 0.8824
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2801 - accuracy: 0.8817
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2800 - accuracy: 0.8804
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2770 - accuracy: 0.8821
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2791 - accuracy: 0.8821
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2770 - accuracy: 0.8817
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2761 - accuracy: 0.8830
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2756 - accuracy: 0.8832
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2744 - accuracy: 0.8851
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2746 - accuracy: 0.8821
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2726 - accuracy: 0.8843
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2720 - accuracy: 0.8851
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2726 - accuracy: 0.8849
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2717 - accuracy: 0.8852
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2710 - accuracy: 0.8839
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2699 - accuracy: 0.8832
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2703 - accuracy: 0.8832
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2692 - accuracy: 0.8871
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2685 - accuracy: 0.8869
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2677 - accuracy: 0.8873
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2665 - accuracy: 0.8882
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2673 - accuracy: 0.8858
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2660 - accuracy: 0.8856
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2662 - accuracy: 0.8852
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2674 - accuracy: 0.8858
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2656 - accuracy: 0.8890
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2639 - accuracy: 0.8890
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2627 - accuracy: 0.8897
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2638 - accuracy: 0.8877
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2623 - accuracy: 0.8894
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2635 - accuracy: 0.8896
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2606 - accuracy: 0.8901
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2608 - accuracy: 0.8901
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2599 - accuracy: 0.8912
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2594 - accuracy: 0.8909
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2592 - accuracy: 0.8903
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2588 - accuracy: 0.8916
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2589 - accuracy: 0.8911
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2573 - accuracy: 0.8897
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2559 - accuracy: 0.8897
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2563 - accuracy: 0.8892
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2544 - accuracy: 0.8950
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2541 - accuracy: 0.8931
Epoch 97/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2545 - accuracy: 0.8909
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2542 - accuracy: 0.8920
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2563 - accuracy: 0.8918
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2528 - accuracy: 0.8916
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4664 - accuracy: 0.7996
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.4130 - accuracy: 0.8256
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8373
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3816 - accuracy: 0.8453
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3635 - accuracy: 0.8530
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3479 - accuracy: 0.8600
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8658
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8652
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8652
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8688
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8680
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3195 - accuracy: 0.8712
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3176 - accuracy: 0.8708
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3150 - accuracy: 0.8731
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8761
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3117 - accuracy: 0.8731
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3092 - accuracy: 0.8751
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3091 - accuracy: 0.8781
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.8772
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3061 - accuracy: 0.8759
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3040 - accuracy: 0.8783
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3025 - accuracy: 0.8765
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3001 - accuracy: 0.8806
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8785
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.8819
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2970 - accuracy: 0.8800
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8787
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2953 - accuracy: 0.8796
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2935 - accuracy: 0.8791
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2940 - accuracy: 0.8808
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2906 - accuracy: 0.8808
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2919 - accuracy: 0.8834
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2881 - accuracy: 0.8815
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2882 - accuracy: 0.8811
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2870 - accuracy: 0.8832
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2858 - accuracy: 0.8836
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2859 - accuracy: 0.8815
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8860
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2835 - accuracy: 0.8840
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2820 - accuracy: 0.8836
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2805 - accuracy: 0.8843
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2811 - accuracy: 0.8843
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2785 - accuracy: 0.8853
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2784 - accuracy: 0.8843
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2775 - accuracy: 0.8877
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2762 - accuracy: 0.8866
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2759 - accuracy: 0.8845
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2738 - accuracy: 0.8853
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2735 - accuracy: 0.8879
Epoch 50/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2727 - accuracy: 0.8886
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2726 - accuracy: 0.8875
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2731 - accuracy: 0.8875
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2713 - accuracy: 0.8881
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2707 - accuracy: 0.8877
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2702 - accuracy: 0.8877
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2695 - accuracy: 0.8868
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2680 - accuracy: 0.8901
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2673 - accuracy: 0.8916
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2653 - accuracy: 0.8900
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2659 - accuracy: 0.8905
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2649 - accuracy: 0.8920
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2639 - accuracy: 0.8920
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2647 - accuracy: 0.8909
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2637 - accuracy: 0.8903
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2620 - accuracy: 0.8924
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2607 - accuracy: 0.8930
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2617 - accuracy: 0.8918
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2591 - accuracy: 0.8937
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2593 - accuracy: 0.8948
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2584 - accuracy: 0.8915
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2586 - accuracy: 0.8928
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2576 - accuracy: 0.8943
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2566 - accuracy: 0.8924
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2559 - accuracy: 0.8948
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2556 - accuracy: 0.8969
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2539 - accuracy: 0.8954
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2537 - accuracy: 0.8933
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2540 - accuracy: 0.8971
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2539 - accuracy: 0.8971
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2533 - accuracy: 0.8945
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2523 - accuracy: 0.8952
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2502 - accuracy: 0.8969
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2510 - accuracy: 0.8973
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2510 - accuracy: 0.8965
Epoch 85/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2488 - accuracy: 0.8995
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2492 - accuracy: 0.8982
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2485 - accuracy: 0.8976
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2475 - accuracy: 0.8965
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2487 - accuracy: 0.8976
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2459 - accuracy: 0.9027
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2475 - accuracy: 0.9003
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2478 - accuracy: 0.8971
Epoch 93/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2449 - accuracy: 0.8988
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2429 - accuracy: 0.8999
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2444 - accuracy: 0.8982
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2451 - accuracy: 0.8988
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2428 - accuracy: 0.8982
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2423 - accuracy: 0.9027
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2412 - accuracy: 0.8997
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2431 - accuracy: 0.8990
84/84 [==============================] - 0s 958us/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.8009
Epoch 2/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3921 - accuracy: 0.8372
Epoch 3/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8562
Epoch 4/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3428 - accuracy: 0.8646
Epoch 5/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3347 - accuracy: 0.8663
Epoch 6/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8650
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3258 - accuracy: 0.8680
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8697
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3173 - accuracy: 0.8699
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3155 - accuracy: 0.8682
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3132 - accuracy: 0.8746
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.8706
Epoch 13/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3086 - accuracy: 0.8734
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8744
Epoch 15/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3023 - accuracy: 0.8772
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.8762
Epoch 17/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2998 - accuracy: 0.8781
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8768
Epoch 19/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2965 - accuracy: 0.8785
Epoch 20/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2957 - accuracy: 0.8811
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2929 - accuracy: 0.8821
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2903 - accuracy: 0.8817
Epoch 23/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2880 - accuracy: 0.8804
Epoch 24/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2896 - accuracy: 0.8815
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2859 - accuracy: 0.8828
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2813 - accuracy: 0.8858
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2836 - accuracy: 0.8847
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2802 - accuracy: 0.8845
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2785 - accuracy: 0.8862
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2763 - accuracy: 0.8852
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2745 - accuracy: 0.8871
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2727 - accuracy: 0.8879
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2718 - accuracy: 0.8871
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2707 - accuracy: 0.8871
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2684 - accuracy: 0.8881
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2650 - accuracy: 0.8890
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2640 - accuracy: 0.8894
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2639 - accuracy: 0.8909
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2602 - accuracy: 0.8926
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2603 - accuracy: 0.8912
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2581 - accuracy: 0.8918
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2571 - accuracy: 0.8941
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2551 - accuracy: 0.8948
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2551 - accuracy: 0.8939
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2513 - accuracy: 0.8997
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2503 - accuracy: 0.8937
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2473 - accuracy: 0.8961
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2466 - accuracy: 0.8942
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2461 - accuracy: 0.8982
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2442 - accuracy: 0.8999
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2453 - accuracy: 0.9002
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2395 - accuracy: 0.9014
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2415 - accuracy: 0.9001
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2365 - accuracy: 0.9031
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2349 - accuracy: 0.9055
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2355 - accuracy: 0.8999
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2322 - accuracy: 0.9057
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2312 - accuracy: 0.9068
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2295 - accuracy: 0.9059
Epoch 60/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2273 - accuracy: 0.9064
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2264 - accuracy: 0.9025
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2283 - accuracy: 0.9025
Epoch 63/100
167/167 [==============================] - 0s 3ms/step - loss: 0.2220 - accuracy: 0.9072
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2247 - accuracy: 0.9102
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2202 - accuracy: 0.9089
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2190 - accuracy: 0.9100
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2174 - accuracy: 0.9100
Epoch 68/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2157 - accuracy: 0.9128
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2180 - accuracy: 0.9089
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2128 - accuracy: 0.9122
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2112 - accuracy: 0.9130
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2112 - accuracy: 0.9126
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2078 - accuracy: 0.9134
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2078 - accuracy: 0.9130
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2082 - accuracy: 0.9136
Epoch 76/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2026 - accuracy: 0.9143
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2066 - accuracy: 0.9152
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2009 - accuracy: 0.9167
Epoch 79/100
167/167 [==============================] - 0s 3ms/step - loss: 0.2030 - accuracy: 0.9152
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1998 - accuracy: 0.9179
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1999 - accuracy: 0.9182
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1997 - accuracy: 0.9166
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1953 - accuracy: 0.9209
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1952 - accuracy: 0.9194
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1957 - accuracy: 0.9199
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1940 - accuracy: 0.9203
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1926 - accuracy: 0.9179
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1897 - accuracy: 0.9227
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1913 - accuracy: 0.9220
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1871 - accuracy: 0.9222
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1874 - accuracy: 0.9211
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1867 - accuracy: 0.9237
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1827 - accuracy: 0.9237
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1840 - accuracy: 0.9222
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1843 - accuracy: 0.9227
Epoch 96/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1809 - accuracy: 0.9280
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1786 - accuracy: 0.9261
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1779 - accuracy: 0.9269
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1763 - accuracy: 0.9297
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1786 - accuracy: 0.9256
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4454 - accuracy: 0.8104
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3920 - accuracy: 0.8380
Epoch 3/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8545
Epoch 4/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3455 - accuracy: 0.8590
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3392 - accuracy: 0.8590
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8646
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8663
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3251 - accuracy: 0.8659
Epoch 9/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3199 - accuracy: 0.8719
Epoch 10/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8702
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8702
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3121 - accuracy: 0.8689
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8744
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.8723
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3048 - accuracy: 0.8772
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3023 - accuracy: 0.8761
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.8714
Epoch 18/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2979 - accuracy: 0.8734
Epoch 19/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2959 - accuracy: 0.8781
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2931 - accuracy: 0.8770
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2928 - accuracy: 0.8794
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2901 - accuracy: 0.8764
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2876 - accuracy: 0.8802
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2880 - accuracy: 0.8796
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2852 - accuracy: 0.8819
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2832 - accuracy: 0.8811
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 0.8811
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2791 - accuracy: 0.8811
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2785 - accuracy: 0.8826
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2762 - accuracy: 0.8817
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2752 - accuracy: 0.8841
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2728 - accuracy: 0.8828
Epoch 33/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2714 - accuracy: 0.8849
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2693 - accuracy: 0.8866
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2693 - accuracy: 0.8862
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2686 - accuracy: 0.8888
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2662 - accuracy: 0.8888
Epoch 38/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2620 - accuracy: 0.8892
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2630 - accuracy: 0.8886
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2606 - accuracy: 0.8901
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2578 - accuracy: 0.8929
Epoch 42/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2566 - accuracy: 0.8926
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2565 - accuracy: 0.8907
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2567 - accuracy: 0.8939
Epoch 45/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2546 - accuracy: 0.8927
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2525 - accuracy: 0.8918
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2504 - accuracy: 0.8961
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2483 - accuracy: 0.8961
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2481 - accuracy: 0.8956
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2453 - accuracy: 0.8948
Epoch 51/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2448 - accuracy: 0.8946
Epoch 52/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2440 - accuracy: 0.8963
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2434 - accuracy: 0.8967
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2401 - accuracy: 0.8967
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2395 - accuracy: 0.9002
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2368 - accuracy: 0.9006
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2380 - accuracy: 0.9002
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2348 - accuracy: 0.9014
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2337 - accuracy: 0.8980
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2358 - accuracy: 0.9008
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2331 - accuracy: 0.8997
Epoch 62/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2313 - accuracy: 0.9025
Epoch 63/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2294 - accuracy: 0.9019
Epoch 64/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2276 - accuracy: 0.9057
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2289 - accuracy: 0.9044
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2272 - accuracy: 0.9017
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2254 - accuracy: 0.9040
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2217 - accuracy: 0.9076
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2218 - accuracy: 0.9061
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2208 - accuracy: 0.9072
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2184 - accuracy: 0.9079
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2174 - accuracy: 0.9092
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2154 - accuracy: 0.9096
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2158 - accuracy: 0.9074
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2170 - accuracy: 0.9083
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2166 - accuracy: 0.9089
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2137 - accuracy: 0.9092
Epoch 78/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2113 - accuracy: 0.9122
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2106 - accuracy: 0.9130
Epoch 80/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2098 - accuracy: 0.9119
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2098 - accuracy: 0.9109
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2068 - accuracy: 0.9137
Epoch 83/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2078 - accuracy: 0.9117
Epoch 84/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2055 - accuracy: 0.9147
Epoch 85/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2043 - accuracy: 0.9167
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2047 - accuracy: 0.9143
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2029 - accuracy: 0.9124
Epoch 88/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2034 - accuracy: 0.9122
Epoch 89/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1998 - accuracy: 0.9132
Epoch 90/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2004 - accuracy: 0.9169
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1972 - accuracy: 0.9149
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1964 - accuracy: 0.9197
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1940 - accuracy: 0.9203
Epoch 94/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1922 - accuracy: 0.9218
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1939 - accuracy: 0.9199
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1930 - accuracy: 0.9177
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1919 - accuracy: 0.9192
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1903 - accuracy: 0.9224
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1929 - accuracy: 0.9173
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1891 - accuracy: 0.9220
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 1ms/step - loss: 0.4576 - accuracy: 0.8000
Epoch 2/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3851 - accuracy: 0.8421
Epoch 3/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3530 - accuracy: 0.8592
Epoch 4/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8661
Epoch 5/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8654
Epoch 6/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3261 - accuracy: 0.8697
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8673
Epoch 8/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3187 - accuracy: 0.8738
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3173 - accuracy: 0.8721
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3132 - accuracy: 0.8776
Epoch 11/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3108 - accuracy: 0.8740
Epoch 12/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3070 - accuracy: 0.8746
Epoch 13/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8765
Epoch 14/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8776
Epoch 15/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3004 - accuracy: 0.8787
Epoch 16/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2961 - accuracy: 0.8800
Epoch 17/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2952 - accuracy: 0.8804
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8783
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2903 - accuracy: 0.8815
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2884 - accuracy: 0.8843
Epoch 21/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2871 - accuracy: 0.8836
Epoch 22/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2849 - accuracy: 0.8825
Epoch 23/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2818 - accuracy: 0.8870
Epoch 24/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2795 - accuracy: 0.8871
Epoch 25/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.8888
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2756 - accuracy: 0.8849
Epoch 27/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2747 - accuracy: 0.8875
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2722 - accuracy: 0.8877
Epoch 29/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2708 - accuracy: 0.8877
Epoch 30/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2692 - accuracy: 0.8896
Epoch 31/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2658 - accuracy: 0.8913
Epoch 32/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2623 - accuracy: 0.8918
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2619 - accuracy: 0.8943
Epoch 34/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2610 - accuracy: 0.8954
Epoch 35/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2585 - accuracy: 0.8933
Epoch 36/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2551 - accuracy: 0.8935
Epoch 37/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2543 - accuracy: 0.8937
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2523 - accuracy: 0.8950
Epoch 39/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2512 - accuracy: 0.8997
Epoch 40/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2479 - accuracy: 0.8997
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2460 - accuracy: 0.9019
Epoch 42/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2438 - accuracy: 0.9004
Epoch 43/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2426 - accuracy: 0.9004
Epoch 44/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2426 - accuracy: 0.9027
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2388 - accuracy: 0.9025
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2358 - accuracy: 0.9036
Epoch 47/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2352 - accuracy: 0.9044
Epoch 48/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2316 - accuracy: 0.9046
Epoch 49/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2324 - accuracy: 0.9063
Epoch 50/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2300 - accuracy: 0.9044
Epoch 51/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2257 - accuracy: 0.9094
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2272 - accuracy: 0.9089
Epoch 53/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2231 - accuracy: 0.9117
Epoch 54/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2220 - accuracy: 0.9115
Epoch 55/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2206 - accuracy: 0.9115
Epoch 56/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2193 - accuracy: 0.9143
Epoch 57/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2178 - accuracy: 0.9141
Epoch 58/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2159 - accuracy: 0.9117
Epoch 59/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2160 - accuracy: 0.9149
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2125 - accuracy: 0.9153
Epoch 61/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2108 - accuracy: 0.9164
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2088 - accuracy: 0.9177
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2116 - accuracy: 0.9139
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2070 - accuracy: 0.9179
Epoch 65/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2084 - accuracy: 0.9160
Epoch 66/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2023 - accuracy: 0.9211
Epoch 67/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2026 - accuracy: 0.9164
Epoch 68/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2008 - accuracy: 0.9216
Epoch 69/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1997 - accuracy: 0.9222
Epoch 70/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1963 - accuracy: 0.9248
Epoch 71/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1971 - accuracy: 0.9214
Epoch 72/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1958 - accuracy: 0.9235
Epoch 73/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1920 - accuracy: 0.9248
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1939 - accuracy: 0.9226
Epoch 75/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1910 - accuracy: 0.9246
Epoch 76/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1912 - accuracy: 0.9243
Epoch 77/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1840 - accuracy: 0.9258
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1832 - accuracy: 0.9276
Epoch 79/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1855 - accuracy: 0.9274
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1827 - accuracy: 0.9271
Epoch 81/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1812 - accuracy: 0.9293
Epoch 82/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1800 - accuracy: 0.9303
Epoch 83/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1805 - accuracy: 0.9280
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1762 - accuracy: 0.9318
Epoch 85/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1777 - accuracy: 0.9303
Epoch 86/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1765 - accuracy: 0.9289
Epoch 87/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1749 - accuracy: 0.9323
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1720 - accuracy: 0.9308
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1689 - accuracy: 0.9319
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1708 - accuracy: 0.9314
Epoch 91/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1690 - accuracy: 0.9323
Epoch 92/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1690 - accuracy: 0.9318
Epoch 93/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1662 - accuracy: 0.9329
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1674 - accuracy: 0.9312
Epoch 95/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1646 - accuracy: 0.9372
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1633 - accuracy: 0.9349
Epoch 97/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1629 - accuracy: 0.9346
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1608 - accuracy: 0.9344
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1641 - accuracy: 0.9340
Epoch 100/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1608 - accuracy: 0.9376
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.4292 - accuracy: 0.8185
Epoch 2/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3675 - accuracy: 0.8522
Epoch 3/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 0.8614
Epoch 4/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3387 - accuracy: 0.8611
Epoch 5/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8672
Epoch 6/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3243 - accuracy: 0.8684
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3246 - accuracy: 0.8674
Epoch 8/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3180 - accuracy: 0.8682
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3109 - accuracy: 0.8734
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3080 - accuracy: 0.8744
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3047 - accuracy: 0.8736
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3008 - accuracy: 0.8764
Epoch 13/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2989 - accuracy: 0.8759
Epoch 14/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2945 - accuracy: 0.8779
Epoch 15/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2894 - accuracy: 0.8809
Epoch 16/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2884 - accuracy: 0.8826
Epoch 17/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2844 - accuracy: 0.8860
Epoch 18/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2799 - accuracy: 0.8858
Epoch 19/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2769 - accuracy: 0.8824
Epoch 20/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2727 - accuracy: 0.8879
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2697 - accuracy: 0.8875
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2675 - accuracy: 0.8897
Epoch 23/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2651 - accuracy: 0.8899
Epoch 24/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2620 - accuracy: 0.8931
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2562 - accuracy: 0.8942
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2537 - accuracy: 0.8944
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2498 - accuracy: 0.8931
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2459 - accuracy: 0.8976
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2423 - accuracy: 0.9004
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2388 - accuracy: 0.9019
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2362 - accuracy: 0.9029
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2345 - accuracy: 0.9019
Epoch 33/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2303 - accuracy: 0.9061
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2269 - accuracy: 0.9077
Epoch 35/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2241 - accuracy: 0.9074
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2188 - accuracy: 0.9111
Epoch 37/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2162 - accuracy: 0.9079
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2164 - accuracy: 0.9100
Epoch 39/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2114 - accuracy: 0.9094
Epoch 40/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2071 - accuracy: 0.9124
Epoch 41/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2033 - accuracy: 0.9158
Epoch 42/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1985 - accuracy: 0.9188
Epoch 43/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1979 - accuracy: 0.9184
Epoch 44/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1958 - accuracy: 0.9188
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1931 - accuracy: 0.9182
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1881 - accuracy: 0.9192
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1834 - accuracy: 0.9227
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1811 - accuracy: 0.9259
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1820 - accuracy: 0.9242
Epoch 50/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1769 - accuracy: 0.9248
Epoch 51/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1740 - accuracy: 0.9304
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1706 - accuracy: 0.9282
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1688 - accuracy: 0.9319
Epoch 54/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1691 - accuracy: 0.9301
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1625 - accuracy: 0.9331
Epoch 56/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1606 - accuracy: 0.9347
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1567 - accuracy: 0.9357
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1531 - accuracy: 0.9379
Epoch 59/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1520 - accuracy: 0.9392
Epoch 60/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1468 - accuracy: 0.9398
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1428 - accuracy: 0.9428
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1451 - accuracy: 0.9422
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1415 - accuracy: 0.9434
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1390 - accuracy: 0.9447
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1362 - accuracy: 0.9417
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1403 - accuracy: 0.9430
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1305 - accuracy: 0.9481
Epoch 68/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1300 - accuracy: 0.9484
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1293 - accuracy: 0.9479
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1244 - accuracy: 0.9520
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1199 - accuracy: 0.9527
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1142 - accuracy: 0.9563
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1217 - accuracy: 0.9529
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1122 - accuracy: 0.9567
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1145 - accuracy: 0.9591
Epoch 76/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1134 - accuracy: 0.9535
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1158 - accuracy: 0.9552
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1063 - accuracy: 0.9601
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1023 - accuracy: 0.9625
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1064 - accuracy: 0.9597
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0991 - accuracy: 0.9606
Epoch 82/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1026 - accuracy: 0.9623
Epoch 83/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0973 - accuracy: 0.9627
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0948 - accuracy: 0.9638
Epoch 85/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0940 - accuracy: 0.9638
Epoch 86/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0925 - accuracy: 0.9638
Epoch 87/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0903 - accuracy: 0.9646
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0864 - accuracy: 0.9677
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0880 - accuracy: 0.9664
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0869 - accuracy: 0.9694
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0851 - accuracy: 0.9689
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0847 - accuracy: 0.9691
Epoch 93/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0878 - accuracy: 0.9647
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0804 - accuracy: 0.9692
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0774 - accuracy: 0.9734
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0794 - accuracy: 0.9724
Epoch 97/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0782 - accuracy: 0.9728
Epoch 98/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0751 - accuracy: 0.9730
Epoch 99/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0709 - accuracy: 0.9756
Epoch 100/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0667 - accuracy: 0.9779
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 5s 1ms/step - loss: 0.4453 - accuracy: 0.8061
Epoch 2/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3678 - accuracy: 0.8500
Epoch 3/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3446 - accuracy: 0.8558
Epoch 4/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8635
Epoch 5/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8584
Epoch 6/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3270 - accuracy: 0.8661
Epoch 7/100
167/167 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8684
Epoch 8/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8659
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3131 - accuracy: 0.8701
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3108 - accuracy: 0.8676
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3076 - accuracy: 0.8712
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3026 - accuracy: 0.8708
Epoch 13/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2991 - accuracy: 0.8787
Epoch 14/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2969 - accuracy: 0.8766
Epoch 15/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2929 - accuracy: 0.8783
Epoch 16/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2890 - accuracy: 0.8809
Epoch 17/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2838 - accuracy: 0.8817
Epoch 18/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2838 - accuracy: 0.8809
Epoch 19/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2776 - accuracy: 0.8843
Epoch 20/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2758 - accuracy: 0.8867
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2737 - accuracy: 0.8847
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2711 - accuracy: 0.8886
Epoch 23/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2656 - accuracy: 0.8914
Epoch 24/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2631 - accuracy: 0.8944
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2604 - accuracy: 0.8914
Epoch 26/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2545 - accuracy: 0.8918
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2508 - accuracy: 0.8946
Epoch 28/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2485 - accuracy: 0.8967
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2464 - accuracy: 0.8978
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2414 - accuracy: 0.9016
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2385 - accuracy: 0.8993
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2345 - accuracy: 0.9004
Epoch 33/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2316 - accuracy: 0.9025
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2329 - accuracy: 0.9010
Epoch 35/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2272 - accuracy: 0.9025
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2247 - accuracy: 0.9047
Epoch 37/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2226 - accuracy: 0.9072
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2170 - accuracy: 0.9077
Epoch 39/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2128 - accuracy: 0.9124
Epoch 40/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2126 - accuracy: 0.9077
Epoch 41/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2049 - accuracy: 0.9143
Epoch 42/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2059 - accuracy: 0.9152
Epoch 43/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2059 - accuracy: 0.9152
Epoch 44/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1999 - accuracy: 0.9182
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1970 - accuracy: 0.9207
Epoch 46/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1956 - accuracy: 0.9145
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1939 - accuracy: 0.9205
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1889 - accuracy: 0.9244
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1828 - accuracy: 0.9242
Epoch 50/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1828 - accuracy: 0.9220
Epoch 51/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1798 - accuracy: 0.9224
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1787 - accuracy: 0.9248
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1784 - accuracy: 0.9287
Epoch 54/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1784 - accuracy: 0.9252
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1712 - accuracy: 0.9316
Epoch 56/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1704 - accuracy: 0.9301
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1703 - accuracy: 0.9280
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1650 - accuracy: 0.9351
Epoch 59/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1642 - accuracy: 0.9334
Epoch 60/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1598 - accuracy: 0.9359
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9374
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1504 - accuracy: 0.9426
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1535 - accuracy: 0.9377
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1533 - accuracy: 0.9402
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1486 - accuracy: 0.9419
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1451 - accuracy: 0.9432
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1437 - accuracy: 0.9451
Epoch 68/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1400 - accuracy: 0.9458
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1430 - accuracy: 0.9411
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1368 - accuracy: 0.9462
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1387 - accuracy: 0.9456
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1358 - accuracy: 0.9473
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1332 - accuracy: 0.9477
Epoch 74/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1335 - accuracy: 0.9466
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1268 - accuracy: 0.9516
Epoch 76/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1244 - accuracy: 0.9520
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1233 - accuracy: 0.9499
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1226 - accuracy: 0.9535
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1178 - accuracy: 0.9522
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1204 - accuracy: 0.9529
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1192 - accuracy: 0.9533
Epoch 82/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1121 - accuracy: 0.9571
Epoch 83/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1114 - accuracy: 0.9589
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1088 - accuracy: 0.9586
Epoch 85/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1104 - accuracy: 0.9569
Epoch 86/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1075 - accuracy: 0.9571
Epoch 87/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1050 - accuracy: 0.9587
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1009 - accuracy: 0.9629
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1010 - accuracy: 0.9644
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0997 - accuracy: 0.9619
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0972 - accuracy: 0.9651
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0937 - accuracy: 0.9677
Epoch 93/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0971 - accuracy: 0.9638
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0974 - accuracy: 0.9623
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.9647
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0905 - accuracy: 0.9659
Epoch 97/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0872 - accuracy: 0.9681
Epoch 98/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0824 - accuracy: 0.9692
Epoch 99/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0887 - accuracy: 0.9676
Epoch 100/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9717
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

167/167 [==============================] - 1s 2ms/step - loss: 0.4219 - accuracy: 0.8225
Epoch 2/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3547 - accuracy: 0.8547
Epoch 3/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8631
Epoch 4/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 0.8678
Epoch 5/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.8682
Epoch 6/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3224 - accuracy: 0.8676
Epoch 7/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3122 - accuracy: 0.8729
Epoch 8/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3142 - accuracy: 0.8721
Epoch 9/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3072 - accuracy: 0.8757
Epoch 10/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3032 - accuracy: 0.8781
Epoch 11/100
167/167 [==============================] - 0s 2ms/step - loss: 0.3016 - accuracy: 0.8772
Epoch 12/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2955 - accuracy: 0.8785
Epoch 13/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2898 - accuracy: 0.8841
Epoch 14/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2895 - accuracy: 0.8815
Epoch 15/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2833 - accuracy: 0.8845
Epoch 16/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2807 - accuracy: 0.8855
Epoch 17/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2773 - accuracy: 0.8873
Epoch 18/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2717 - accuracy: 0.8905
Epoch 19/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2726 - accuracy: 0.8886
Epoch 20/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2689 - accuracy: 0.8892
Epoch 21/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2637 - accuracy: 0.8948
Epoch 22/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2614 - accuracy: 0.8954
Epoch 23/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2579 - accuracy: 0.8928
Epoch 24/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2535 - accuracy: 0.8967
Epoch 25/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2529 - accuracy: 0.8995
Epoch 26/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2455 - accuracy: 0.8999
Epoch 27/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2431 - accuracy: 0.9038
Epoch 28/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2421 - accuracy: 0.9016
Epoch 29/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2386 - accuracy: 0.9038
Epoch 30/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2334 - accuracy: 0.9074
Epoch 31/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2291 - accuracy: 0.9076
Epoch 32/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2276 - accuracy: 0.9061
Epoch 33/100
167/167 [==============================] - 0s 1ms/step - loss: 0.2213 - accuracy: 0.9081
Epoch 34/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2217 - accuracy: 0.9076
Epoch 35/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2181 - accuracy: 0.9104
Epoch 36/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2149 - accuracy: 0.9136
Epoch 37/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2119 - accuracy: 0.9104
Epoch 38/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2069 - accuracy: 0.9123
Epoch 39/100
167/167 [==============================] - 0s 2ms/step - loss: 0.2064 - accuracy: 0.9154
Epoch 40/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1999 - accuracy: 0.9149
Epoch 41/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1974 - accuracy: 0.9188
Epoch 42/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1979 - accuracy: 0.9199
Epoch 43/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1921 - accuracy: 0.9226
Epoch 44/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1899 - accuracy: 0.9226
Epoch 45/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1871 - accuracy: 0.9235
Epoch 46/100
167/167 [==============================] - 0s 1ms/step - loss: 0.1822 - accuracy: 0.9263
Epoch 47/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1812 - accuracy: 0.9274
Epoch 48/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1770 - accuracy: 0.9293
Epoch 49/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1747 - accuracy: 0.9273
Epoch 50/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1715 - accuracy: 0.9299
Epoch 51/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1665 - accuracy: 0.9319
Epoch 52/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1711 - accuracy: 0.9293
Epoch 53/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1626 - accuracy: 0.9368
Epoch 54/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1600 - accuracy: 0.9372
Epoch 55/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1556 - accuracy: 0.9361
Epoch 56/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1567 - accuracy: 0.9357
Epoch 57/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1554 - accuracy: 0.9357
Epoch 58/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9406
Epoch 59/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1480 - accuracy: 0.9398
Epoch 60/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1455 - accuracy: 0.9424
Epoch 61/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1457 - accuracy: 0.9421
Epoch 62/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1377 - accuracy: 0.9458
Epoch 63/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1356 - accuracy: 0.9484
Epoch 64/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1368 - accuracy: 0.9466
Epoch 65/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1323 - accuracy: 0.9473
Epoch 66/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1288 - accuracy: 0.9509
Epoch 67/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1282 - accuracy: 0.9511
Epoch 68/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1255 - accuracy: 0.9511
Epoch 69/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1246 - accuracy: 0.9522
Epoch 70/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1222 - accuracy: 0.9501
Epoch 71/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1233 - accuracy: 0.9518
Epoch 72/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1179 - accuracy: 0.9571
Epoch 73/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1157 - accuracy: 0.9567
Epoch 74/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1119 - accuracy: 0.9589
Epoch 75/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1106 - accuracy: 0.9576
Epoch 76/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1081 - accuracy: 0.9593
Epoch 77/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1090 - accuracy: 0.9595
Epoch 78/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1046 - accuracy: 0.9586
Epoch 79/100
167/167 [==============================] - 0s 2ms/step - loss: 0.1049 - accuracy: 0.9619
Epoch 80/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0997 - accuracy: 0.9633
Epoch 81/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0997 - accuracy: 0.9625
Epoch 82/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0940 - accuracy: 0.9668
Epoch 83/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0989 - accuracy: 0.9640
Epoch 84/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0950 - accuracy: 0.9633
Epoch 85/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0911 - accuracy: 0.9687
Epoch 86/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0881 - accuracy: 0.9685
Epoch 87/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0877 - accuracy: 0.9696
Epoch 88/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0913 - accuracy: 0.9646
Epoch 89/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0841 - accuracy: 0.9713
Epoch 90/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0826 - accuracy: 0.9687
Epoch 91/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0838 - accuracy: 0.9685
Epoch 92/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0876 - accuracy: 0.9668
Epoch 93/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0831 - accuracy: 0.9689
Epoch 94/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0766 - accuracy: 0.9726
Epoch 95/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0751 - accuracy: 0.9758
Epoch 96/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0798 - accuracy: 0.9713
Epoch 97/100
167/167 [==============================] - 0s 1ms/step - loss: 0.0739 - accuracy: 0.9753
Epoch 98/100
167/167 [==============================] - 0s 1ms/step - loss: 0.0733 - accuracy: 0.9747
Epoch 99/100
167/167 [==============================] - 0s 1ms/step - loss: 0.0741 - accuracy: 0.9721
Epoch 100/100
167/167 [==============================] - 0s 2ms/step - loss: 0.0684 - accuracy: 0.9783
84/84 [==============================] - 0s 1ms/step
Epoch 1/100

/home/hp/Documents/GenAI/DeepLearning/lib/python3.8/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

250/250 [==============================] - 1s 1ms/step - loss: 0.5184 - accuracy: 0.7460
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4122 - accuracy: 0.8259
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3883 - accuracy: 0.8401
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3673 - accuracy: 0.8528
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3539 - accuracy: 0.8571
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3473 - accuracy: 0.8608
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3426 - accuracy: 0.8593
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8616
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8621
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.8630
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8644
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8644
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8636
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8641
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8627
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8655
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8659
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8654
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8662
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8658
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3278 - accuracy: 0.8680
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8669
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8658
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3257 - accuracy: 0.8664
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3259 - accuracy: 0.8692
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8660
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3236 - accuracy: 0.8669
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3239 - accuracy: 0.8665
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8683
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8668
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8668
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8669
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3230 - accuracy: 0.8684
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3218 - accuracy: 0.8689
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.8680
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3214 - accuracy: 0.8687
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3211 - accuracy: 0.8683
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8698
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3208 - accuracy: 0.8683
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8694
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3196 - accuracy: 0.8701
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3194 - accuracy: 0.8687
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3191 - accuracy: 0.8686
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3190 - accuracy: 0.8696
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8706
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3172 - accuracy: 0.8706
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3179 - accuracy: 0.8699
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8679
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3167 - accuracy: 0.8689
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8695
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8669
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3162 - accuracy: 0.8716
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3160 - accuracy: 0.8709
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3155 - accuracy: 0.8705
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8720
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8694
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8711
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3141 - accuracy: 0.8705
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3137 - accuracy: 0.8700
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3133 - accuracy: 0.8691
Epoch 61/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3131 - accuracy: 0.8725
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3123 - accuracy: 0.8709
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3109 - accuracy: 0.8715
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8725
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8715
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8711
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3114 - accuracy: 0.8704
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3099 - accuracy: 0.8715
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.8723
Epoch 70/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3095 - accuracy: 0.8709
Epoch 71/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3088 - accuracy: 0.8721
Epoch 72/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3083 - accuracy: 0.8726
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3092 - accuracy: 0.8721
Epoch 74/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8742
Epoch 75/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8726
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3076 - accuracy: 0.8731
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3065 - accuracy: 0.8759
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3065 - accuracy: 0.8751
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3064 - accuracy: 0.8741
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8749
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3054 - accuracy: 0.8746
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3050 - accuracy: 0.8759
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3058 - accuracy: 0.8746
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.8763
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3051 - accuracy: 0.8745
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8750
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3049 - accuracy: 0.8750
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3040 - accuracy: 0.8758
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3030 - accuracy: 0.8741
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3037 - accuracy: 0.8765
Epoch 91/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8740
Epoch 92/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3029 - accuracy: 0.8749
Epoch 93/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8763
Epoch 94/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3024 - accuracy: 0.8764
Epoch 95/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3022 - accuracy: 0.8765
Epoch 96/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8746
Epoch 97/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3025 - accuracy: 0.8788
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3010 - accuracy: 0.8766
Epoch 99/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3004 - accuracy: 0.8764
Epoch 100/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8758
Best :0.862249 using {'epochs': 100, 'layers': 1, 'neurons': 64}